/*
 * Prices are in MAJOR units: `amount: 1899` means ₹1899, not ₹18.99. See the
 * note at the top of dogs.ts — do not divide these by 100.
 */
/* eslint-disable @medusajs/prices-in-major-units */

/**
 * Cats branch of the KUDL catalog. Every `column` / `item` pair must exist in
 * catsMenu in lib/taxonomy.ts — seed-kudl-catalog.ts validates and throws
 * otherwise. Brand names are demo values drawn from the taxonomy's Popular
 * Brands column; no partnership is implied.
 *
 * No `breeds` on any cat product: the storefront's Shop By Breed lineup
 * (homeContent.ts BREEDS) is a dog breed list, so claiming a breed here would
 * put cats behind a Golden Retriever filter.
 */

import { CatalogProduct } from "./types"

export const catProducts: CatalogProduct[] = [
  // ─── Cat Food ────────────────────────────────────────────────────────────
  {
    title: "Whiskas Adult Dry Food — Ocean Fish",
    handle: "whiskas-adult-dry-food-ocean-fish",
    petType: "cats",
    tree: "cats",
    column: "Cat Food",
    item: "Dry Food",
    brand: "Whiskas",
    category: "food",
    rating: 4.3,
    reviewCount: 3218,
    image: "kibbleCloseup",
    weight: 1200,
    description:
      "A complete everyday dry diet for cats over one year, built on ocean fish and fortified for the things an indoor cat's body works hardest at. Cats are obligate carnivores, so the protein level here is deliberately higher than any dog food, and taurine is added rather than assumed — a cat cannot synthesise enough of it and a deficiency damages the heart muscle and the retina. Omega-6 and zinc support coat condition, and a controlled magnesium level with urine-acidifying ingredients helps keep the urinary tract healthy, which is the single most common reason a male cat ends up at an emergency clinic. The kibble is small and triangular so it is easy to crunch. Feed measured portions rather than free-feeding a bowl left out all day, keep fresh water beside it always, and remember that a cat on dry food alone gets very little moisture from its meals.",
    variants: [
      { title: "480g", sku: "KUDL-CAT-WHISKAS-DRY-480G", amount: 219 },
      { title: "1.2kg", sku: "KUDL-CAT-WHISKAS-DRY-1.2KG", amount: 469 },
      { title: "3kg", sku: "KUDL-CAT-WHISKAS-DRY-3KG", amount: 1099 },
    ],
  },
  {
    title: "Sheba Rich Premium Wet Food — Tuna in Gravy",
    handle: "sheba-rich-premium-tuna-gravy",
    petType: "cats",
    tree: "cats",
    column: "Cat Food",
    item: "Wet Food",
    brand: "Sheba",
    category: "food",
    rating: 4.6,
    reviewCount: 2077,
    image: "wetFoodBowl",
    weight: 420,
    description:
      "Fine flakes of tuna in a light gravy, portioned into single-serve pouches. Wet food deserves more room in a cat's diet than it usually gets, and the reason is water: cats evolved to take most of their moisture from prey and have a famously weak thirst drive, so a cat fed only kibble often runs mildly dehydrated for years — the background condition behind a great deal of feline urinary and kidney disease. A pouch is roughly three-quarters water, which is the easiest way to raise intake without persuading a cat to drink more. The strong aroma also makes it the reliable option for a fussy cat, a cat off its food after a stressful week, or a senior whose sense of smell has dulled. Complete and balanced on its own, and equally good stirred through kibble. Serve at room temperature, refrigerate leftovers covered and use within a day.",
    variants: [
      { title: "Pack of 6 × 70g", sku: "KUDL-CAT-SHEBA-6PK", amount: 349 },
      { title: "Pack of 12 × 70g", sku: "KUDL-CAT-SHEBA-12PK", amount: 649 },
      { title: "Pack of 24 × 70g", sku: "KUDL-CAT-SHEBA-24PK", amount: 1199 },
    ],
  },
  {
    title: "Whiskas Kitten Dry Food — Ocean Fish",
    handle: "whiskas-kitten-dry-food",
    petType: "cats",
    tree: "cats",
    column: "Cat Food",
    item: "Kitten Food",
    brand: "Whiskas",
    category: "food",
    rating: 4.4,
    reviewCount: 1611,
    image: "kibbleBowlWood",
    weight: 1200,
    description:
      "A growth diet for kittens from weaning to twelve months, when a cat multiplies its birth weight many times over and needs far more protein, energy and calcium per kilo than it ever will again. DHA supports brain and vision development through the weeks when a kitten is learning fastest, and a boosted vitamin E and antioxidant blend backs up an immune system still building its own defences. The kibble is tiny and thin-walled so small jaws can manage it, and it softens quickly if you moisten it with warm water for a kitten only just off milk. Feed little and often — four small meals a day up to six months, then three, then twice daily as an adult — because a kitten's stomach cannot hold a day's calories in one sitting. Keep water available at all times, and switch to an adult diet at around a year rather than leaving a grown cat on a high-calorie kitten food.",
    variants: [
      { title: "480g", sku: "KUDL-CAT-WHISKAS-KIT-480G", amount: 249 },
      { title: "1.2kg", sku: "KUDL-CAT-WHISKAS-KIT-1.2KG", amount: 519 },
    ],
  },
  {
    title: "Farmina N&D Prime Chicken & Pomegranate Adult Cat",
    handle: "farmina-nd-prime-chicken-cat",
    petType: "cats",
    tree: "cats",
    column: "Cat Food",
    item: "Premium Food",
    brand: "Farmina N&D",
    category: "food",
    rating: 4.8,
    reviewCount: 494,
    image: "kibbleBowlBlue",
    weight: 1500,
    description:
      "A grain-free, high-protein premium diet where animal ingredients make up seventy percent of the recipe — a formulation much closer to what a cat is actually built to digest than a cereal-heavy kibble. Deboned chicken and herring supply the amino acids, taurine is included at a generous level, and pomegranate and blueberry contribute polyphenols with antioxidant activity. Removing maize, wheat and rice cuts the carbohydrate load, which is the reasoning behind a low-carb diet for an overweight indoor cat or a cat with a diabetic tendency, and it also takes the usual cereal suspects out of the picture during an elimination trial for a food sensitivity. The kibble is dense and calorie-rich, so the correct daily portion looks small — weigh it rather than eyeballing a scoop, and reduce it further for a cat that is already heavy. Transition over seven to ten days; cats resist an abrupt change harder than dogs do.",
    variants: [
      { title: "300g", sku: "KUDL-CAT-FARMINA-300G", amount: 549 },
      { title: "1.5kg", sku: "KUDL-CAT-FARMINA-1.5KG", amount: 2099 },
    ],
  },

  // ─── Cat Treats ──────────────────────────────────────────────────────────
  {
    title: "Sheba Creamy Lickable Treat — Chicken",
    handle: "sheba-creamy-lickable-treat-chicken",
    petType: "cats",
    tree: "cats",
    column: "Cat Treats",
    item: "Creamy Treats",
    brand: "Sheba",
    category: "treats",
    rating: 4.7,
    reviewCount: 1884,
    image: "catTakingTreat",
    weight: 90,
    description:
      "A smooth, spoonable purée in single-serve tubes that a cat licks straight from your hand. The format is the point: almost no cat refuses it, which makes a lickable treat the most useful tool in the house for the moments when you need cooperation rather than obedience — holding a cat still for a brush-out, distracting one during a nail trim, keeping a nervous cat occupied while a vet listens to its chest, or hiding a crushed tablet in something it will genuinely swallow. It is also a gentle way to get calories and moisture into a cat that has gone off solid food. Roughly six calories a tube, so it will not unbalance the day's feeding. Squeeze a little at a time rather than emptying the tube, keep it as a reward tied to something you want to happen again, and refrigerate an opened tube and use it the same day.",
    variants: [
      { title: "Pack of 4 × 15g", sku: "KUDL-CAT-CREAMY-4PK", amount: 199 },
      { title: "Pack of 12 × 15g", sku: "KUDL-CAT-CREAMY-12PK", amount: 529 },
    ],
  },
  {
    title: "Carniwel Chicken Jerky Slivers for Cats",
    handle: "carniwel-chicken-jerky-slivers-cats",
    petType: "cats",
    tree: "cats",
    column: "Cat Treats",
    item: "Jerky Treats",
    brand: "Carniwel",
    category: "treats",
    rating: 4.4,
    reviewCount: 736,
    image: "catTakingTreat",
    weight: 70,
    description:
      "Whole chicken breast, sliced into thin slivers and air-dried, with nothing else in the pack. Single-ingredient treats earn their place for a specific reason: when a cat is being worked up for a suspected food sensitivity, almost every commercial treat undoes the elimination diet, and a pure protein sliver is the one thing you can still hand over. The drying leaves a chewy, intensely meaty piece that most cats work at rather than swallowing whole, which makes it last. Grain-free, no added colour or preservative, no cereal binder. Tear a sliver into two or three pieces — a cat's whole daily allowance for treats is small, and ten percent of a cat's calories is far less food than owners tend to imagine. Reseal the pouch and store it cool and dry. Not suitable during an elimination trial if chicken is the protein under suspicion.",
    variants: [
      { title: "35g", sku: "KUDL-CAT-JERKY-35G", amount: 249 },
      { title: "70g", sku: "KUDL-CAT-JERKY-70G", amount: 449 },
    ],
  },
  {
    title: "Whiskas Crunchy Pockets — Chicken & Cheese",
    handle: "whiskas-crunchy-pockets",
    petType: "cats",
    tree: "cats",
    column: "Cat Treats",
    item: "Crunchy Treats",
    brand: "Whiskas",
    category: "treats",
    rating: 4.5,
    reviewCount: 2296,
    image: "catTakingTreat",
    weight: 60,
    description:
      "Small crunchy shells with a soft savoury centre, so a cat gets a snap and then a burst of flavour from the same piece — a contrast that holds the interest of cats which quickly tire of a one-texture treat. Each piece is around two calories, which makes them the practical currency for the many small transactions of living with a cat: coming when called, tolerating a carrier, letting you look in an ear. The crunchy outer shell gives the teeth a light mechanical scrub as the cat bites through, a modest benefit rather than a substitute for dental care. Fortified with taurine and vitamin E. Scatter a few pieces to make a cat hunt for them rather than handing the lot over in one go; a foraging cat gets more out of the same six treats. Reseal the pack and keep all treats under a tenth of the day's calories.",
    variants: [
      { title: "60g", sku: "KUDL-CAT-CRUNCHY-60G", amount: 179 },
      { title: "3 × 60g", sku: "KUDL-CAT-CRUNCHY-180G", amount: 479 },
    ],
  },
  {
    title: "Drools Hairball Control Treats with Fibre",
    handle: "drools-hairball-control-treats",
    petType: "cats",
    tree: "cats",
    column: "Cat Treats",
    item: "Healthy Treats",
    brand: "Drools",
    category: "treats",
    rating: 4.2,
    reviewCount: 617,
    image: "catTakingTreat",
    weight: 80,
    description:
      "A functional treat built around beet pulp and psyllium fibre, aimed at the swallowed hair a cat accumulates from grooming itself. Fibre helps that hair pass through the gut rather than collect in the stomach and come back up, which is the mechanism behind a hairball — and it is a genuine nuisance for long-haired cats, for cats that over-groom, and for every cat during a heavy moult. Salmon oil supplies omega-3 to support the skin, on the reasoning that a coat shedding less into a cat's mouth is the better fix. Fortified with vitamin E and taurine. A couple of pieces a day is the intended dose; this reduces frequency rather than eliminating hairballs. Brushing remains the more effective half of the job. Retching that produces nothing, repeated vomiting, or a cat off its food warrants a vet rather than more fibre, since those signs can point to a blockage.",
    variants: [{ title: "80g", sku: "KUDL-CAT-HAIRBALL-80G", amount: 299 }],
  },

  // ─── Cat Litter Supplies ─────────────────────────────────────────────────
  {
    title: "Scoopy Bentonite Clumping Litter — Unscented",
    handle: "scoopy-bentonite-clumping-litter",
    petType: "cats",
    tree: "cats",
    column: "Cat Litter Supplies",
    item: "Litter",
    brand: "Scoopy",
    category: "litter-habitat",
    rating: 4.6,
    reviewCount: 4102,
    image: "catLitterBox",
    weight: 5000,
    description:
      "Sodium bentonite clay in a fine, sand-like grain that seals into a hard clump within minutes of contact with urine, so the whole soiled portion lifts out on a scoop and the rest of the tray stays usable. That is the practical case for a clumping litter over a non-clumping one: you remove waste instead of stirring it in, so the same tray of litter lasts weeks and stays genuinely clean rather than merely dry. Odour is controlled by trapping ammonia inside the sealed clump rather than by masking it with perfume. The grain is deliberately fine because most cats prefer a soft, sand-like substrate underfoot — litter texture is one of the most common reasons a cat starts going elsewhere. Low dust for a clay litter. Fill to a depth of five to seven centimetres, scoop daily, top up weekly and change out fully once a month. Never flush clumping clay.",
    variants: [
      { title: "5kg", sku: "KUDL-CAT-SCOOPY-5KG", amount: 549 },
      { title: "10kg", sku: "KUDL-CAT-SCOOPY-10KG", amount: 999 },
    ],
  },
  {
    title: "Scoopy Lavender Scented Clumping Litter",
    handle: "scoopy-lavender-scented-litter",
    petType: "cats",
    tree: "cats",
    column: "Cat Litter Supplies",
    item: "Scented Litter",
    brand: "Scoopy",
    category: "litter-habitat",
    rating: 4.1,
    reviewCount: 1288,
    image: "catLitterBox",
    weight: 5000,
    description:
      "The same fine-grain bentonite clumping formula with a light lavender fragrance released as the litter is disturbed, for households where the tray has to sit somewhere the smell would otherwise be noticed — a small flat, a bathroom, a corner of a studio. Be clear-eyed about the trade-off, though: the perfume is there for the human in the room, and a meaningful minority of cats dislike a scented substrate and will quietly start using a rug instead. If your cat is at all fussy, or has ever had a house-soiling episode, buy the unscented version. Where a cat does accept it, the fragrance is deliberately mild rather than floral, and it works alongside the clumping action rather than as a substitute for scooping — no scent covers a tray that has not been cleaned. Fill five to seven centimetres deep, scoop daily and replace fully each month.",
    variants: [
      { title: "5kg", sku: "KUDL-CAT-SCOOPY-LAV-5KG", amount: 599 },
      { title: "10kg", sku: "KUDL-CAT-SCOOPY-LAV-10KG", amount: 1099 },
    ],
  },
  {
    title: "KUDL Tofu Flushable Clumping Litter",
    handle: "kudl-tofu-flushable-litter",
    petType: "cats",
    tree: "cats",
    column: "Cat Litter Supplies",
    item: "Flushable Litter",
    brand: "KUDL Essentials",
    category: "litter-habitat",
    rating: 4.3,
    reviewCount: 842,
    image: "catLitterBox",
    weight: 2500,
    description:
      "Litter pellets extruded from pea and soy fibre left over from tofu production — a plant substrate rather than mined clay. Two things follow from that. It is flushable in small amounts, a few clumps at a time, which removes the weekly bin bag of soiled clay from a flat with no easy outdoor bin. And it weighs roughly half what an equivalent volume of bentonite does, which is a real difference if you carry litter up stairs. It clumps firmly, absorbs several times its own weight, and produces very little dust, making it a sensible choice around a cat or a person with a respiratory sensitivity. Fill to about six centimetres, scoop daily, and flush no more than a few clumps at a time with a full cistern — check that your building's plumbing and local rules permit it, and bin it instead if there is any doubt.",
    variants: [
      { title: "2.5kg", sku: "KUDL-CAT-TOFU-2.5KG", amount: 649 },
      { title: "2 × 2.5kg", sku: "KUDL-CAT-TOFU-5KG", amount: 1199 },
    ],
  },
  {
    title: "KUDL Hooded Litter Box with Swing Door",
    handle: "kudl-hooded-litter-box",
    petType: "cats",
    tree: "cats",
    column: "Cat Litter Supplies",
    item: "Litter Boxes & Toilets",
    brand: "KUDL Essentials",
    category: "litter-habitat",
    rating: 4.4,
    reviewCount: 1027,
    image: "catLitterBox",
    weight: 2200,
    description:
      "A covered tray with a hinged swing door and a removable carbon filter in the roof, sized generously enough that a full-grown cat can turn around inside without touching the walls — the usual mistake with a hooded box is buying one a cat has to reverse out of. The hood does two useful things: it keeps kicked litter inside instead of across the floor, and it gives a shy cat privacy, which matters in a busy household or where a dog takes an unwelcome interest. It also contains odour, helped by the filter. Some cats genuinely dislike an enclosed tray, so if yours hesitates, take the door off first and then the lid rather than concluding the box was a mistake. The top lifts clear off for scooping and washing, and a lip around the base catches stray granules. As a rule of thumb keep one tray per cat plus one, and wash the box with mild soap monthly.",
    variants: [
      { title: "Standard", sku: "KUDL-CAT-LITTERBOX-STD", amount: 1799 },
      { title: "Large", sku: "KUDL-CAT-LITTERBOX-L", amount: 2299 },
    ],
  },
  {
    title: "KUDL Litter Deodorizer Powder — Fragrance Free",
    handle: "kudl-litter-deodorizer-powder",
    petType: "cats",
    tree: "cats",
    column: "Cat Litter Supplies",
    item: "Cleaning & Deodorizers",
    brand: "KUDL Essentials",
    category: "litter-habitat",
    rating: 4.2,
    reviewCount: 573,
    image: "catLitterBox",
    weight: 500,
    description:
      "A fine powder of activated charcoal, baking soda and zeolite that you sprinkle across a clean tray before adding litter. It works by adsorption rather than by masking — the porous zeolite and charcoal trap ammonia molecules and the baking soda neutralises acid, so the smell is chemically captured instead of covered over with perfume. That distinction is why this is fragrance-free: a scented additive is exactly the kind of change that makes a fussy cat abandon its tray, and a cat that stops using the box is a far worse problem than a faint smell. Safe if a paw picks some up, and it does not interfere with clumping. Use two tablespoons per tray, reapply when you top the litter up, and treat it as a supplement to daily scooping rather than a way to scoop less. A persistent strong ammonia smell from one cat is worth a vet visit.",
    variants: [{ title: "500g", sku: "KUDL-CAT-DEODORIZER-500G", amount: 399 }],
  },
  {
    title: "KUDL Litter Scoop & Waste Bag Set",
    handle: "kudl-litter-scoop-waste-bag-set",
    petType: "cats",
    tree: "cats",
    column: "Cat Litter Supplies",
    item: "Scooper & Waste Disposal",
    brand: "KUDL Essentials",
    category: "litter-habitat",
    rating: 4.3,
    reviewCount: 691,
    image: "catLitterBox",
    weight: 400,
    description:
      "A deep metal scoop with a long handle and narrow slots, plus a roll of one hundred and twenty tie-handle waste bags and a wall hook to keep both off the floor. The slot width is the detail that matters: too wide and clean litter falls through with the clumps, wasting a bag a week; too narrow and it clogs. These are cut to pass fine bentonite granules and hold a soft clump intact. The handle is long enough to reach the back of a hooded tray without putting your knuckles in it, and the metal blade will not flex and break a clump the way a thin plastic scoop does. The bags are thick enough not to tear on a hard clump and knot closed to contain the smell in an indoor bin. Scoop at least once daily — most cats will avoid a tray that has not been cleaned, and daily scooping is also how you notice a change in urine volume early.",
    variants: [{ title: "Scoop + 120 bags", sku: "KUDL-CAT-SCOOPSET-120", amount: 449 }],
  },

  // ─── Cat Toys ────────────────────────────────────────────────────────────
  {
    title: "Skatrs Feather Teaser Wand",
    handle: "skatrs-feather-teaser-wand",
    petType: "cats",
    tree: "cats",
    column: "Cat Toys",
    item: "Cat Teasers",
    brand: "Skatrs",
    category: "toys",
    rating: 4.7,
    reviewCount: 2431,
    image: "catStretching",
    weight: 90,
    description:
      "A flexible wand with a length of cord and a feather lure, and the single most effective toy you can own for an indoor cat — because it lets you imitate prey. A cat's play drive follows a hunting sequence of stare, stalk, chase, pounce and kill, and a wand is the only toy that lets you run that whole sequence: drag the lure away from the cat and let it disappear behind furniture rather than waving it in the cat's face, which is the mistake that makes cats lose interest within a minute. Two short sessions a day of ten minutes does more for an indoor cat's weight and boredom than any amount of toys left on the floor. Always finish by letting the cat catch the lure, then feed it — an unresolved hunt leaves a cat frustrated. Put the wand away between sessions, both to keep it novel and because a loose cord is a swallowing hazard.",
    variants: [
      { title: "Feather lure", sku: "KUDL-CAT-WAND-FEATHER", amount: 249 },
      { title: "Feather + ribbon set", sku: "KUDL-CAT-WAND-SET", amount: 399 },
    ],
  },
  {
    title: "KUDL Rolling Ball Track Tower",
    handle: "kudl-rolling-ball-track-tower",
    petType: "cats",
    tree: "cats",
    column: "Cat Toys",
    item: "Ball & Chaser Toys",
    brand: "KUDL Essentials",
    category: "toys",
    rating: 4.4,
    reviewCount: 918,
    image: "catWithButterfly",
    weight: 700,
    description:
      "A three-tier tower with balls captive in circular tracks, so a cat can bat them round and round without ever sending one under the sofa. That sounds trivial and is not: a loose ball is fun for about forty seconds before it vanishes, whereas a captive track keeps producing movement for as long as the cat keeps swatting, which is what makes this one of the few toys a cat will genuinely use alone. The tiers are staggered so a paw reaching in on one level nudges a ball on another, and the balls are textured for grip and unweighted so they respond to a light tap. The base is wide and heavy enough not to tip when a cat leans on it. Assembles in a minute with no tools. Rotate it out of sight for a week every so often — novelty is most of the value of any solo toy — and wipe it clean with a damp cloth.",
    variants: [{ title: "3-tier", sku: "KUDL-CAT-BALLTRACK-3T", amount: 899 }],
  },
  {
    title: "KUDL Catnip Mice — Pack of 4",
    handle: "kudl-catnip-mice-4pk",
    petType: "cats",
    tree: "cats",
    column: "Cat Toys",
    item: "Catnip Toys",
    brand: "KUDL Essentials",
    category: "toys",
    rating: 4.5,
    reviewCount: 1663,
    image: "catStretching",
    weight: 60,
    description:
      "Four small felt mice with long tails, stuffed with dried catnip and a rustling insert. Catnip works through nepetalactone, a volatile compound a cat takes in through the nose that produces a few minutes of rolling, rubbing and boisterous play, followed by a mellow period — harmless, non-addictive, and self-limiting because a cat's receptors stop responding for an hour or two afterwards. Roughly a third of cats have no genetic response to it at all, which is worth knowing before you conclude a toy is faulty. The mice are sized and weighted for a cat to carry in its mouth and hind-paw kick, and the rustle keeps the interest of cats indifferent to the herb. Squeeze a mouse to release fresh oils when the response fades, store the spares in a sealed bag to keep them potent, and replace a mouse once a seam opens.",
    variants: [{ title: "Pack of 4", sku: "KUDL-CAT-CATNIPMICE-4PK", amount: 349 }],
  },
  {
    title: "Skatrs Plush Kicker Toy with Catnip",
    handle: "skatrs-plush-kicker-toy",
    petType: "cats",
    tree: "cats",
    column: "Cat Toys",
    item: "Plush Toys",
    brand: "Skatrs",
    category: "toys",
    rating: 4.3,
    reviewCount: 774,
    image: "catLounging",
    weight: 120,
    description:
      "A long, soft-bodied plush tube filled with polyester fibre and a pocket of catnip, made for the specific behaviour cats show with captured prey: gripping it with the front legs and raking it with the hind feet. A kicker is sized for that — around twenty-five centimetres, roughly the length of a cat's own body — which is why cats wrestle one for far longer than they bother with a small mouse. It also gives a cat an acceptable target for that raking instinct, which is a useful redirection for the cats that otherwise practise it on your forearm during play. Double-stitched seams, no plastic eyes or glued-on parts to come loose, and machine washable in a laundry bag on a cool cycle. Replace it once a seam opens and fibre starts coming out, and keep it as a play toy rather than leaving it out permanently.",
    variants: [{ title: "25cm", sku: "KUDL-CAT-KICKER-25CM", amount: 449 }],
  },
  {
    title: "KUDL Sisal Cat Tree with Scratching Posts",
    handle: "kudl-sisal-cat-tree",
    petType: "cats",
    tree: "cats",
    column: "Cat Toys",
    item: "Cat Trees & Scratchers",
    brand: "KUDL Essentials",
    category: "toys",
    rating: 4.6,
    reviewCount: 1156,
    image: "kittenScratcher",
    weight: 8500,
    description:
      "A multi-level tree with sisal-wrapped posts, a covered cubby and a top perch. Both halves earn their keep. Scratching is not optional behaviour a cat can be trained out of — it sheds the outer nail sheath, stretches the back and shoulders, and marks territory with scent from the paw pads — so the practical question is only whether the cat does it on sisal or on your sofa arm. Vertical space matters just as much: a cat that can get up high has somewhere to retreat from a dog, a toddler or a visitor, and height is one of the most reliable ways to reduce tension between cats sharing a flat. The posts are tall enough for a full stretch, which a short scratcher does not allow. Site it where the cat already scratches rather than in a spare corner, and near a window if you can. Sturdy base, tool-light assembly, replaceable sisal.",
    variants: [
      { title: "Medium (90cm)", sku: "KUDL-CAT-TREE-90", amount: 3299 },
      { title: "Large (140cm)", sku: "KUDL-CAT-TREE-140", amount: 4999 },
    ],
  },
  {
    title: "KUDL Motion-Activated Laser Play Robot",
    handle: "kudl-motion-laser-play-robot",
    petType: "cats",
    tree: "cats",
    column: "Cat Toys",
    item: "Smart & Interactive Toys",
    brand: "KUDL Essentials",
    category: "toys",
    rating: 4.0,
    reviewCount: 486,
    image: "catWithButterfly",
    weight: 340,
    description:
      "A rotating laser unit that projects a moving dot in randomised patterns across the floor and walls, with an auto-off timer after fifteen minutes and a motion sensor that wakes it when a cat walks past. It is genuinely useful for the hours nobody is home, giving a bored indoor cat a burst of real running rather than another nap. One caveat worth taking seriously: a laser dot can never be caught, and for some cats that produces visible frustration and obsessive light-chasing afterwards. The fix is simple — end a laser session by landing the dot on a physical treat or a toy the cat can actually pounce on, so the hunt resolves. Never shine it at a cat's eyes or a person's. Class 1 low-power laser with a fixed downward angle. Runs on USB-C or three AA cells, with adjustable speed and a quiet motor.",
    variants: [{ title: "Standard", sku: "KUDL-CAT-LASER-STD", amount: 1499 }],
  },

  // ─── Cat Walk & Travel Supplies ──────────────────────────────────────────
  {
    title: "Skatrs Breakaway Collar with Bell",
    handle: "skatrs-breakaway-collar-with-bell",
    petType: "cats",
    tree: "cats",
    column: "Cat Walk & Travel Supplies",
    item: "Collars",
    brand: "Skatrs",
    category: "accessories",
    rating: 4.4,
    reviewCount: 1042,
    image: "whiteMaineCoon",
    weight: 40,
    description:
      "A lightweight nylon collar with a breakaway safety buckle — the one feature that makes a collar acceptable on a cat at all. Cats climb, squeeze through gaps and jump onto things, and a collar that does not release will eventually catch on a branch, a fence or a latch; a breakaway clasp pops open under sustained pull so the cat frees itself. Never fit a cat with a dog collar for exactly this reason. The webbing is soft-edged and narrow so it disappears into the coat, and a small removable bell gives wildlife a fraction of a second's warning, which measurably reduces what an outdoor cat catches. There is a D-ring for an identity tag, which remains the fastest route home for a lost cat. Fit so two fingers slide under it flat, check it monthly, and remove the bell if the sound bothers your cat.",
    variants: [
      { title: "Kitten (17-25cm)", sku: "KUDL-CAT-COLLAR-KIT", amount: 299 },
      { title: "Adult (20-30cm)", sku: "KUDL-CAT-COLLAR-AD", amount: 349 },
    ],
  },
  {
    title: "KUDL Engraved ID Tag & Bell Set",
    handle: "kudl-engraved-id-tag-bell-set",
    petType: "cats",
    tree: "cats",
    column: "Cat Walk & Travel Supplies",
    item: "Bells & Tags",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.5,
    reviewCount: 638,
    image: "whiteMaineCoon",
    weight: 20,
    description:
      "A stainless steel identity tag with laser engraving on both faces, supplied with a split ring and two spare bells. An engraved tag is the least glamorous and most effective piece of equipment a cat can wear: a microchip needs a scanner and a trip to a vet or shelter, whereas a phone number on a tag lets the neighbour who finds your cat in their garage call you within the minute. Laser engraving cuts into the steel rather than printing on it, so the number is still legible after a year of weather — the failure mode of a cheap stamped or painted tag. Steel rather than aluminium so it will not bend or corrode. Keep it short: a name and one phone number reads better than four crowded lines. The tag is light enough not to bother a cat, and the split ring goes onto a breakaway collar. Check the engraving is still readable every few months.",
    variants: [
      { title: "Round 20mm", sku: "KUDL-CAT-IDTAG-R20", amount: 349 },
      { title: "Bone 25mm", sku: "KUDL-CAT-IDTAG-B25", amount: 349 },
    ],
  },
  {
    title: "Skatrs Escape-Proof Cat Harness & Leash Set",
    handle: "skatrs-escape-proof-cat-harness-set",
    petType: "cats",
    tree: "cats",
    column: "Cat Walk & Travel Supplies",
    item: "Harnesses",
    brand: "Skatrs",
    category: "accessories",
    rating: 4.2,
    reviewCount: 559,
    image: "harnessBlue",
    weight: 150,
    description:
      "A padded mesh vest-style harness with a matching lead, designed around the fact that cats reverse out of anything loose. Coverage across the chest and shoulders spreads the load and leaves nothing pulling on the throat, and four independent adjustment points let you fit the neck and girth separately — the gap that a cat exploits is almost always a neck strap set for a body girth. A vest is markedly harder to escape than a thin two-strap H-harness. Never clip a lead to a cat's collar; a breakaway collar is designed to release, which is the opposite of what you want on a walk. Introduce it slowly: let the cat wear it indoors with treats for several short sessions across a week before the lead goes on, and expect a first outing to be a few minutes in a quiet corner rather than a walk. Never leave a harness on an unsupervised cat.",
    variants: [
      { title: "Small", sku: "KUDL-CAT-HARNESS-S", amount: 699 },
      { title: "Medium", sku: "KUDL-CAT-HARNESS-M", amount: 799 },
    ],
  },
  {
    title: "KUDL Hard-Shell Cat Carrier with Top Load",
    handle: "kudl-hardshell-cat-carrier",
    petType: "cats",
    tree: "cats",
    column: "Cat Walk & Travel Supplies",
    item: "Carriers & Travel Supplies",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.6,
    reviewCount: 874,
    image: "catInCarrier",
    weight: 2400,
    description:
      "A rigid carrier with a front grille door and a second opening in the roof, which is the feature that changes vet visits. A cat that has braced itself in the back of a carrier cannot be dragged out forwards without a fight, but it can be lifted calmly out of the top — and the roof panel also unclips entirely, so a vet can examine a nervous cat sitting in the bottom half of its own carrier rather than on a strange steel table. Ventilated on three sides, with a seatbelt slot to stop it sliding around a car, and a washable pad in the base. Metal latches rather than plastic clips. The real trick is to leave the carrier out at home with a blanket in it all year, so it is furniture rather than a warning sign; a cat that only sees it on the way to a clinic will hide from it every time. Wipes clean with mild soap.",
    variants: [
      { title: "Medium", sku: "KUDL-CAT-CARRIER-M", amount: 2199 },
      { title: "Large", sku: "KUDL-CAT-CARRIER-L", amount: 2699 },
    ],
  },

  // ─── Cat Clothing ────────────────────────────────────────────────────────
  {
    title: "KUDL Soft Cotton Cat Tee",
    handle: "kudl-soft-cotton-cat-tee",
    petType: "cats",
    tree: "cats",
    column: "Cat Clothing",
    item: "Tshirts & Shirts",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 3.9,
    reviewCount: 214,
    image: "catOnStairs",
    weight: 70,
    description:
      "A lightweight stretch-cotton tee cut narrow through the body for a cat's shape, with generous armholes so the shoulder blades still slide freely — a cat moves through its shoulders far more than a dog does, and a garment that binds there will be shrugged off within a minute. Beyond the obvious, a thin shirt has one properly practical use: it stops a cat worrying at a healing surgical site or a treated patch of skin, and most cats tolerate a soft tee far better than the plastic cone that would otherwise be the alternative. It also catches a good deal of loose hair during a moult. Flatlock seams so nothing rubs a shaved belly, and no buttons or loose trim to be chewed off. Measure back length and chest girth before ordering. Introduce it for a few minutes at a time with treats, never leave a cat in it unsupervised, and remove it in the heat.",
    variants: [
      { title: "Small", sku: "KUDL-CAT-TEE-S", amount: 449 },
      { title: "Medium", sku: "KUDL-CAT-TEE-M", amount: 499 },
    ],
  },
  {
    title: "KUDL Reversible Cat Bandana — Pack of 2",
    handle: "kudl-reversible-cat-bandana-2pk",
    petType: "cats",
    tree: "cats",
    column: "Cat Clothing",
    item: "Bandanas & Bowties",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.1,
    reviewCount: 302,
    image: "catLounging",
    weight: 40,
    description:
      "Two reversible cotton bandanas that slip onto a collar you have already fitted, rather than tying around the neck. For a cat that distinction is a safety matter, not a convenience: anything knotted around a cat's throat has no way to release if it snags on a branch or a gate, whereas a slip-on rides on a breakaway collar that will pop open under load. Cut small and light so the fabric does not swamp a cat or restrict its head, hemmed on every edge to stop the cotton fraying, and pre-washed so the shape holds. Double-sided for four looks from two pieces. There is a modest practical upside too — a patterned cat is easier to spot at dusk in a garden. Fits collars up to fifteen millimetres. Machine wash cold. Take it off for unsupervised time, and stop using it if your cat scratches at its neck.",
    variants: [{ title: "Pack of 2", sku: "KUDL-CAT-BANDANA-2PK", amount: 299 }],
  },

  // ─── Bowls & Feeders ─────────────────────────────────────────────────────
  {
    title: "KUDL Tilted Steel Cat Bowl — Whisker Friendly",
    handle: "kudl-tilted-steel-cat-bowl",
    petType: "cats",
    tree: "cats",
    column: "Bowls & Feeders",
    item: "Steel Bowls",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.6,
    reviewCount: 1489,
    image: "catAtBowl",
    weight: 320,
    description:
      "A shallow, wide stainless steel dish set at a fifteen-degree tilt in a silicone-footed stand. Both design choices come from the same observation: cats dislike pressing their whiskers against the sides of a bowl, and a deep narrow dish is the most common reason a cat paws food out onto the floor or walks away from a half-finished meal. Wide and shallow lets the whiskers stay clear, and the tilt brings food to the low edge so a cat can reach the last of it without craning its neck down — worth more with each year for an older cat with a stiff neck or arthritic elbows. Steel rather than plastic because it does not scratch into bacteria-harbouring grooves, does not leach, and can be washed hot enough to sanitise. The silicone base keeps the bowl still. Dishwasher safe. Wash daily — a cat's water bowl grows a biofilm within about twenty-four hours.",
    variants: [
      { title: "Single bowl", sku: "KUDL-CAT-TILTBOWL-1", amount: 549 },
      { title: "Twin bowls", sku: "KUDL-CAT-TILTBOWL-2", amount: 899 },
    ],
  },
  {
    title: "KUDL Gravity Food & Water Dispenser — 3L",
    handle: "kudl-gravity-food-water-dispenser",
    petType: "cats",
    tree: "cats",
    column: "Bowls & Feeders",
    item: "Food & Water Dispenser",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.1,
    reviewCount: 517,
    image: "catAtBowl",
    weight: 900,
    description:
      "A twin-hopper gravity dispenser holding three litres of dry food on one side and three litres of water on the other, topping up the bowls automatically as they empty. No motor, no batteries, nothing to fail — which is the argument for gravity over an electronic feeder if all you need is cover for a long working day or a weekend when a neighbour is looking in once. The hoppers are food-grade BPA-free plastic and lift off the base for washing, and a wide footprint keeps the unit stable when a cat leans in. Be aware of the trade-off: gravity feeding is free-feeding, so it does not suit a cat that needs portion control to manage its weight, and it will not tell you if a cat stops eating. Rinse the water side daily and wash both hoppers weekly. Do not leave a cat alone for more than a couple of days regardless of how much food is in it.",
    variants: [{ title: "3L + 3L", sku: "KUDL-CAT-GRAVITY-3L", amount: 1299 }],
  },
  {
    title: "KUDL Silicone Licky Mat for Cats",
    handle: "kudl-silicone-licky-mat-cats",
    petType: "cats",
    tree: "cats",
    column: "Bowls & Feeders",
    item: "Slow Feeders & Licky mats",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.4,
    reviewCount: 826,
    image: "catAtBowl",
    weight: 180,
    description:
      "A food-grade silicone mat with a shallow textured relief, meant for spreading wet food, a lickable purée or plain yoghurt across so a cat has to work it out of the grooves with its tongue. Two things come out of that. A pouch that would vanish in twenty seconds becomes five or ten minutes of activity, which is real enrichment for an indoor cat and takes the edge off mealtime pushiness. And the repetitive licking is genuinely calming for most cats, which makes a loaded mat one of the better tools for a nervous cat during a thunderstorm, a house move, or the ten minutes before a carrier appears. Suction feet hold it to a tile floor or the side of a bath, which is why it doubles as a distraction during grooming. Freeze it loaded for a longer session in hot weather. Dishwasher safe, and rinse it before food dries hard in the relief.",
    variants: [{ title: "Standard", sku: "KUDL-CAT-LICKYMAT-STD", amount: 399 }],
  },

  // ─── Cat Grooming ────────────────────────────────────────────────────────
  {
    title: "KUDL No-Rinse Waterless Cat Shampoo",
    handle: "kudl-no-rinse-waterless-cat-shampoo",
    petType: "cats",
    tree: "cats",
    column: "Cat Grooming",
    item: "Shampoos & Conditioners",
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.3,
    reviewCount: 1204,
    image: "shampooBottles",
    weight: 220,
    description:
      "A pH-balanced foaming cleanser you work into the coat and towel out, with no rinsing and no bath. For most cats that is the whole point: a healthy cat grooms itself effectively and does not need bathing, and forcing one into water is a genuinely distressing event for the cat and often a scratched forearm for you. A waterless foam handles the situations that do come up — a greasy patch along the spine on a long-haired cat, something sticky on the fur, a senior or an overweight cat that can no longer reach its own back, or a kitten that has sat in something. Aloe and oatmeal are included to settle the skin, and there is no alcohol, no perfume and no sulphate. Work it in with your fingers or a damp cloth against the lie of the coat, then towel out. Keep it clear of the eyes, ears and mouth. Never use a dog shampoo or any dog flea product on a cat.",
    variants: [{ title: "200ml", sku: "KUDL-CAT-NORINSE-200ML", amount: 449 }],
  },
  {
    title: "Skatrs Deshedding Comb for Cats",
    handle: "skatrs-deshedding-comb-cats",
    petType: "cats",
    tree: "cats",
    column: "Cat Grooming",
    item: "Brushes & Combs",
    brand: "Skatrs",
    category: "grooming-health",
    rating: 4.7,
    reviewCount: 2588,
    image: "fluffyCatCoat",
    weight: 190,
    description:
      "A stainless steel deshedding blade with fine rounded teeth, set in a non-slip handle, for pulling the loose undercoat out before the cat swallows it. That is the argument for brushing a cat that already grooms itself perfectly well: everything a cat licks out of its coat goes down its throat, and the less hair it swallows the fewer hairballs come back up. Brushing also prevents matting, which starts as shed hair trapped against the skin and, once felted, has to be cut out — painful and expensive if it reaches the point of a sedated clip. The teeth are spaced to lift dead hair while sliding past the guard coat, and each tip is rounded so it does not score skin that is much thinner than a dog's. Work in short strokes in the direction the coat lies, keep sessions to a few minutes, and skip the belly and armpits unless your cat truly tolerates it.",
    variants: [
      { title: "Small", sku: "KUDL-CAT-DESHED-S", amount: 399 },
      { title: "Large", sku: "KUDL-CAT-DESHED-L", amount: 499 },
    ],
  },
  {
    title: "KUDL Ear & Eye Cleaning Wipes for Cats",
    handle: "kudl-ear-eye-cleaning-wipes-cats",
    petType: "cats",
    tree: "cats",
    column: "Cat Grooming",
    item: "Ear & eye care",
    pharmacyItem: { column: "Cats (Pharmacy)", item: "Ear & Eye Care" },
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.2,
    reviewCount: 691,
    image: "shampooBottles",
    weight: 180,
    description:
      "Soft lint-free pads pre-moistened with a sterile saline and boric acid solution, for the routine cleaning of tear staining under the eyes and visible wax at the opening of the ear. Flat-faced breeds like Persians need this regularly, since a shortened tear duct means fluid runs down the face instead of draining, and dried discharge left in place irritates the skin beneath it. Use one pad per eye and wipe outward from the inner corner, never across both eyes, so an infection in one is not carried to the other. For ears, clean only the outer flap and the visible opening — never push a pad, a cotton bud or anything else into the canal, which is easy to damage and easy to pack wax deeper into. This is routine hygiene, not treatment: head shaking, a bad smell, dark crumbly discharge, squinting or a cloudy eye needs a vet the same week.",
    variants: [{ title: "50 wipes", sku: "KUDL-CAT-EYEWIPES-50", amount: 299 }],
  },
  {
    title: "KUDL Cat Nail Clipper — Curved Blade",
    handle: "kudl-cat-nail-clipper-curved",
    petType: "cats",
    tree: "cats",
    column: "Cat Grooming",
    item: "Trimmers & Nail Clippers",
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.5,
    reviewCount: 947,
    image: "brushesInBowl",
    weight: 90,
    description:
      "A small scissor-style clipper with curved stainless blades that cradle a cat's thin, sharply hooked claw, so the cut follows the natural shape instead of crushing the nail flat the way a straight blade does. Sharpness matters more than anything else here — a blunt clipper splits the claw and hurts, and a cat only needs one bad experience to fight the process for years. Trimming the hooked tips every two or three weeks blunts the damage to furniture and to your arms, and it prevents the real problem in older cats, where a claw left to grow curls round and grows into the pad. Press gently on the toe to extend the claw and cut only the clear hook, staying well short of the pink quick. Do two or three claws and stop rather than insisting on all eighteen. Keep styptic powder to hand in case of a nick. Never declaw.",
    variants: [{ title: "Standard", sku: "KUDL-CAT-CLIPPER-STD", amount: 349 }],
  },

  // ─── Beds, Mats & Tents ──────────────────────────────────────────────────
  {
    title: "KUDL Plush Donut Cuddler Bed",
    handle: "kudl-plush-donut-cuddler-bed",
    petType: "cats",
    tree: "cats",
    column: "Beds, Mats & Tents",
    item: "Beds",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.7,
    reviewCount: 1932,
    image: "catsCuddling",
    weight: 1100,
    description:
      "A round bed with a deep raised rim in a soft faux-fur, the shape most cats reliably choose for themselves. The rim is doing real work rather than looking pretty: it gives a cat something to tuck against and rest its chin on, and enclosing the body on all sides conserves heat and satisfies the instinct to sleep somewhere with its back covered. Cats prefer a warm ambient temperature well above the one we set our rooms to, which is why they end up in boxes and on laptops — a soft-walled nest is the easiest way to give them somewhere better. Filled with recycled polyester fibre over a non-slip base, and the whole bed goes in the machine, which matters for the hair and dander that build up in any bed a cat uses daily. Put it somewhere warm, quiet and slightly elevated rather than in a busy corridor, and wash it cold and tumble dry low.",
    variants: [
      { title: "50cm", sku: "KUDL-CAT-DONUT-50", amount: 1199 },
      { title: "60cm", sku: "KUDL-CAT-DONUT-60", amount: 1499 },
    ],
  },
  {
    title: "KUDL Foldable Cat House Tent",
    handle: "kudl-foldable-cat-house-tent",
    petType: "cats",
    tree: "cats",
    column: "Beds, Mats & Tents",
    item: "Cat Houses",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.4,
    reviewCount: 663,
    image: "catLounging",
    weight: 1300,
    description:
      "A soft-sided enclosed tent with a single round entrance and a removable cushion, giving a cat somewhere it cannot be seen. That is the specific value of a covered bed over an open one, and it is worth more than it looks: a cat under stress — a house move, building work, a new baby, a visiting dog — settles fastest when it has a hiding place it chooses itself, and a cat with somewhere to retreat shows fewer stress behaviours than one with no option but the top of a wardrobe. The single small entrance is deliberate; it means a cat inside can watch one direction and does not have to guard its back. It folds flat in seconds for travel, which makes it a familiar-smelling refuge in a hotel room or at a relative's house. Cushion and shell are both machine washable. Site it against a wall in a quiet corner, and never pull a cat out of it as a punishment.",
    variants: [{ title: "Standard", sku: "KUDL-CAT-TENT-STD", amount: 1399 }],
  },
  {
    title: "KUDL Self-Warming Thermal Cushion",
    handle: "kudl-self-warming-thermal-cushion",
    petType: "cats",
    tree: "cats",
    column: "Beds, Mats & Tents",
    item: "Blankets & Cushions",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.3,
    reviewCount: 588,
    image: "catsCuddling",
    weight: 600,
    description:
      "A flat cushion with a metallic thermal layer sandwiched between soft fleece, which reflects a cat's own body heat back rather than letting it sink away into the floor. No cable, no plug and nothing to overheat, so it is safe to leave with an unsupervised cat and safe on a windowsill. This is genuinely useful for the cats that feel cold most: thin or short-coated breeds, kittens, seniors and cats recovering from illness, all of which spend a good part of a cold night looking for somewhere warm and often settle for a radiator ledge or a laptop. Slim enough to lay inside a carrier, a cat tree cubby, a cardboard box or on a hard chair, which is usually where a cat wants it. The fleece cover unzips and machine washes cold; do not tumble dry, as heat can crease the reflective layer and it stops working. Warmth builds over a few minutes of the cat lying on it.",
    variants: [
      { title: "45×35cm", sku: "KUDL-CAT-THERMAL-S", amount: 699 },
      { title: "60×45cm", sku: "KUDL-CAT-THERMAL-L", amount: 899 },
    ],
  },

  // ─── Health & Wellness ──────────────────────────────────────────────────
  {
    title: "KUDL Skin & Coat Omega Supplement for Cats",
    handle: "kudl-skin-coat-omega-supplement-cats",
    petType: "cats",
    tree: "cats",
    column: "Health & Wellness",
    item: "Supplements",
    pharmacyItem: { column: "Supplements", item: "Skin & coat supplements" },
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.4,
    reviewCount: 742,
    image: "prescriptionBottle",
    weight: 120,
    description:
      "A pump-bottle liquid of salmon and krill oil standardised for EPA and DHA, with vitamin E added both as an antioxidant and to protect the oil from going rancid in the bottle. Omega-3 fatty acids have a well-supported anti-inflammatory action in the skin, which is why they are a common recommendation alongside veterinary treatment for a dull coat, flaky skin, seasonal itching and excessive shedding — and the same anti-inflammatory effect is why they are often suggested for older cats with stiff joints. Improvement in a coat takes six to eight weeks to become visible, because you are waiting on new hair to grow rather than on the existing coat to change, so give it a full course before judging it. Pump the daily dose by weight over wet food. Refrigerate after opening and use within two months. Introduce it gradually — too much oil too quickly loosens the stool — and check with your vet first for a cat with pancreatitis or on a fat-restricted diet.",
    variants: [
      { title: "100ml", sku: "KUDL-CAT-OMEGA-100ML", amount: 649 },
      { title: "250ml", sku: "KUDL-CAT-OMEGA-250ML", amount: 1299 },
    ],
  },
  {
    title: "KUDL Broad-Spectrum Dewormer Tablets for Cats",
    handle: "kudl-dewormer-tablets-cats",
    petType: "cats",
    tree: "cats",
    column: "Health & Wellness",
    item: "Deworming",
    pharmacyItem: { column: "Preventive Care", item: "Dewormers" },
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.6,
    reviewCount: 1315,
    image: "blisterPacks",
    weight: 30,
    description:
      "A palatable broad-spectrum tablet covering the intestinal worms cats actually pick up — roundworm, hookworm and tapeworm. Regular worming matters more than most owners assume, and for two reasons. Cats acquire worms routinely, from hunting, from fleas they swallow while grooming, and kittens from their mother's milk, and a burden is usually invisible until it is heavy enough to cause a pot-bellied kitten, poor coat, weight loss or vomiting. And several of these worms are zoonotic, so worming the cat also protects the children in the house. Typical guidance is every three months for an adult cat and monthly for kittens from three weeks to six months, but follow your vet's schedule for your cat's lifestyle — a hunter needs more frequent treatment than a strictly indoor cat. Dose strictly by weight; weigh the cat rather than guessing. Give with a little food, and treat the fleas at the same time, since a flea infestation reliably re-seeds tapeworm.",
    variants: [
      { title: "2 tablets", sku: "KUDL-CAT-DEWORM-2T", amount: 299 },
      { title: "4 tablets", sku: "KUDL-CAT-DEWORM-4T", amount: 529 },
    ],
  },
  {
    title: "KUDL Cat Tick & Flea Spot-On Solution",
    handle: "kudl-cat-tick-flea-spot-on",
    petType: "cats",
    tree: "cats",
    column: "Health & Wellness",
    item: "Anti Tick & Fleas",
    pharmacyItem: { column: "Preventive Care", item: "Tick and flea" },
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.5,
    reviewCount: 1088,
    image: "dogWithBottle",
    weight: 30,
    description:
      "A monthly topical for cats, applied to the skin at the back of the neck where the cat cannot reach to lick it — placement is the whole design, since anything a cat can groom off is both ineffective and a poisoning risk. It spreads through the coat's oil layer and kills fleas and ticks on contact for around four weeks. Fleas are worth taking seriously in cats beyond the itching: a heavy burden causes anaemia in a kitten, flea bite hypersensitivity is a leading cause of the scabby over-grooming vets see, and a swallowed flea passes on tapeworm. The critical warning is this: never use a dog spot-on on a cat. Permethrin-based dog products are severely toxic to cats and cause tremors and seizures, including from close contact with a recently treated dog. Dose by weight band, keep the cat dry for forty-eight hours, treat every pet in the house the same day, and wash all bedding hot.",
    variants: [
      { title: "Under 4kg — 3 pipettes", sku: "KUDL-CAT-SPOTON-S3", amount: 599 },
      { title: "Over 4kg — 3 pipettes", sku: "KUDL-CAT-SPOTON-L3", amount: 699 },
    ],
  },
]
