/*
 * Prices are in MAJOR units: `amount: 1899` means ₹1899, not ₹18.99. Medusa
 * v2's pricing module stores and returns decimal major units for INR, so these
 * must not be multiplied by 100. The @medusajs/prices-in-major-units lint rule
 * assumes any 3-4 digit integer is a minor-unit mistake, which is wrong for
 * rupee pricing where every realistic price looks like that.
 */
/* eslint-disable @medusajs/prices-in-major-units */

/**
 * Dogs branch of the KUDL catalog. Every `column` / `item` pair must exist in
 * dogsMenu in lib/taxonomy.ts — seed-kudl-catalog.ts validates and throws
 * otherwise. Brand names are demo values drawn from the taxonomy's Popular
 * Brands column; no partnership is implied.
 */

import { CatalogProduct } from "./types"

const ALL_BREEDS = [
  "golden-retriever",
  "german-shepherd",
  "labrador",
  "rottweiler",
  "beagle",
  "shih-tzu",
  "boxer",
]

const SMALL_BREEDS = ["shih-tzu", "beagle"]
const LARGE_BREEDS = ["golden-retriever", "german-shepherd", "labrador", "rottweiler", "boxer"]

export const dogProducts: CatalogProduct[] = [
  // ─── Dog Food ────────────────────────────────────────────────────────────
  {
    title: "Pedigree Adult Complete Dry Food — Chicken & Vegetables",
    handle: "pedigree-adult-complete-dry-food",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Food",
    item: "Dry Food",
    brand: "Pedigree",
    category: "food",
    breeds: ALL_BREEDS,
    rating: 4.3,
    reviewCount: 2841,
    image: "kibbleBowlWood",
    weight: 3000,
    description:
      "A complete and balanced everyday diet for adult dogs over one year, built around real chicken as the first protein source and finished with a garden vegetable blend. Each kibble is fortified with a 4-in-1 nutrition system: omega-6 fatty acids and zinc for a soft, glossy coat, calcium and phosphorus in a controlled ratio for strong bones and teeth, natural fibre and prebiotics for regular digestion, and a vitamin E and antioxidant complex to support the immune system. The kibble is extruded to a medium size and moderate crunch, which suits most breeds from a Beagle up to a Labrador and encourages proper chewing rather than gulping. Free from artificial flavours and added sugar. Feed as the sole diet with fresh drinking water always available, and transition over five to seven days by mixing with your dog's current food to let the gut adjust comfortably.",
    variants: [
      { title: "1.2kg", sku: "KUDL-DOG-PED-DRY-1.2KG", amount: 349 },
      { title: "3kg", sku: "KUDL-DOG-PED-DRY-3KG", amount: 799 },
      { title: "10kg", sku: "KUDL-DOG-PED-DRY-10KG", amount: 2299 },
    ],
  },
  {
    title: "Pedigree Chicken & Liver Chunks in Gravy",
    handle: "pedigree-chicken-liver-chunks-gravy",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Food",
    item: "Wet Food",
    brand: "Pedigree",
    category: "food",
    breeds: ALL_BREEDS,
    rating: 4.4,
    reviewCount: 1163,
    image: "wetFoodBowl",
    weight: 400,
    description:
      "Tender chunks of chicken and liver simmered in a savoury gravy, portioned into single-serve pouches so every meal is opened fresh. Wet food carries roughly seventy-five percent moisture, which makes it a genuinely useful choice for dogs that drink too little, dogs recovering from illness, and fussy eaters who need the aroma of a warm meal to get interested in the bowl. The soft texture is also kind to senior dogs and to any dog with worn or missing teeth. Nutritionally complete on its own, it works equally well as a topper stirred through dry kibble to lift palatability without unbalancing the diet. Serve at room temperature for the fullest aroma, refrigerate any unused portion in a covered container, and use it within twenty-four hours. No artificial colours or preservatives.",
    variants: [
      { title: "Pack of 6 × 70g", sku: "KUDL-DOG-PED-WET-6PK", amount: 299 },
      { title: "Pack of 12 × 70g", sku: "KUDL-DOG-PED-WET-12PK", amount: 549 },
    ],
  },
  {
    title: "Drools Puppy Starter Dry Food",
    handle: "drools-puppy-starter-dry-food",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Food",
    item: "Puppy Food",
    brand: "Drools",
    category: "food",
    breeds: ALL_BREEDS,
    rating: 4.2,
    reviewCount: 1974,
    image: "kibbleCloseup",
    weight: 3000,
    description:
      "A high-density growth formula for puppies from weaning through to twelve months, when a puppy builds most of its adult frame and needs considerably more protein, energy and minerals per kilo of bodyweight than a grown dog. Chicken and egg supply highly digestible protein for muscle development, while DHA sourced from fish oil supports brain and retinal development during the critical socialisation window. Calcium and phosphorus are held in a controlled ratio to grow bone at a safe rate — over-supplementing either mineral is a real risk in fast-growing large breeds. The kibble is small and softens quickly in warm water, which makes it easy to serve as a porridge to very young puppies still moving off milk. Split the daily ration across three or four meals until six months of age, then reduce to two.",
    variants: [
      { title: "1.2kg", sku: "KUDL-DOG-DROOLS-PUP-1.2KG", amount: 399 },
      { title: "3kg", sku: "KUDL-DOG-DROOLS-PUP-3KG", amount: 899 },
    ],
  },
  {
    title: "Farmina N&D Grain Free Chicken & Pomegranate",
    handle: "farmina-nd-grain-free-chicken-pomegranate",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Food",
    item: "Grain Free Food",
    brand: "Farmina N&D",
    category: "food",
    breeds: ALL_BREEDS,
    rating: 4.7,
    reviewCount: 612,
    image: "kibbleBowlBlue",
    weight: 2500,
    description:
      "A high-protein, grain-free recipe for adult dogs, where seventy percent of the ingredients are animal-derived and the remaining thirty percent comes from vegetables, fruits and botanicals rather than from cereal fillers. Deboned chicken and dehydrated chicken supply the amino acid profile a working muscle actually uses; pomegranate and sweet orange contribute polyphenols with antioxidant activity. Removing wheat, maize and rice lowers the carbohydrate load and is often the first change a vet suggests when investigating a suspected cereal sensitivity that presents as itchy skin, recurrent ear trouble or loose stools. Because the calorie density is high, the correct portion is noticeably smaller than for a supermarket kibble — weigh the ration rather than using a scoop by eye, and reduce it further for a dog that is already carrying extra weight.",
    variants: [
      { title: "800g", sku: "KUDL-DOG-FARMINA-GF-800G", amount: 899 },
      { title: "2.5kg", sku: "KUDL-DOG-FARMINA-GF-2.5KG", amount: 2399 },
    ],
  },
  {
    title: "Henlo Baked Chicken & Brown Rice Dry Food",
    handle: "henlo-baked-chicken-brown-rice",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Food",
    item: "Baked Dry Food",
    brand: "Henlo",
    category: "food",
    breeds: ALL_BREEDS,
    rating: 4.6,
    reviewCount: 1488,
    image: "kibbleBowlWood",
    weight: 3000,
    description:
      "Slow-baked rather than high-pressure extruded, which is the whole point of this food. Baking at a lower temperature for longer preserves more of the nutrients that harsh processing degrades, and it produces a denser, crumblier kibble that dogs have to actually chew — so meals last longer and gulping is less likely. Fresh deboned chicken leads the recipe, supported by brown rice for slow-release energy, pumpkin and beetroot pulp for fibre, and a live probiotic culture added after baking so the cultures survive to reach the gut. There is no rendered meat meal, no artificial colour and no added sugar. The lower moisture content of a baked kibble means a little goes further, so start at about eighty percent of the volume you fed of a previous extruded food and adjust from your dog's weight and condition over a fortnight.",
    variants: [
      { title: "1kg", sku: "KUDL-DOG-HENLO-BAKED-1KG", amount: 649 },
      { title: "3kg", sku: "KUDL-DOG-HENLO-BAKED-3KG", amount: 1749 },
      { title: "8kg", sku: "KUDL-DOG-HENLO-BAKED-8KG", amount: 4199 },
    ],
  },
  {
    title: "Drools Veg Adult Dry Food",
    handle: "drools-veg-adult-dry-food",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Food",
    item: "Veg Dog Food",
    brand: "Drools",
    category: "food",
    breeds: ALL_BREEDS,
    rating: 4.0,
    reviewCount: 743,
    image: "kibbleCloseup",
    weight: 3000,
    description:
      "A vegetarian complete diet for adult dogs, formulated for households that keep a meat-free kitchen and for dogs whose diet has to exclude common animal proteins during an elimination trial. Protein comes from soy and pea concentrate blended to cover the essential amino acids a dog cannot make itself, and the recipe is supplemented with taurine, L-carnitine, vitamin B12 and iron — the nutrients most likely to fall short when meat is removed. Milk solids and a vegetable oil blend supply fat and the omega-6 needed for skin and coat condition. This is a legitimate maintenance diet for a healthy adult dog, but it is not appropriate for puppies, pregnant or nursing bitches, or hard-working dogs with high energy demands. If your dog is on a vegetarian diet long term, ask your vet to check body condition and bloodwork at the annual visit.",
    variants: [
      { title: "1.2kg", sku: "KUDL-DOG-DROOLS-VEG-1.2KG", amount: 329 },
      { title: "3kg", sku: "KUDL-DOG-DROOLS-VEG-3KG", amount: 749 },
    ],
  },
  {
    title: "Kennel Kitchen Fresh Chicken & Rice Meal",
    handle: "kennel-kitchen-fresh-chicken-rice-meal",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Food",
    item: "Fresh Food",
    brand: "Kennel Kitchen",
    category: "food",
    breeds: ALL_BREEDS,
    rating: 4.5,
    reviewCount: 431,
    image: "wetFoodBowl",
    weight: 500,
    description:
      "Gently cooked whole-food meals made in small batches from human-grade chicken, rice, carrot and spinach, then chilled rather than shelf-stabilised. Nothing here is rendered, and there is no kibble-style extrusion step, so the ingredients arrive looking like the food they came from. Fresh food is the easiest way to raise the moisture and palatability of a diet at once, which makes it a strong option for dogs that have gone off their kibble, dogs on the mend after a procedure, and seniors whose appetite has faded. Portioned into daily sachets and sized by your dog's weight. Keep frozen until the day before serving, thaw overnight in the refrigerator, serve at room temperature, and use an opened sachet within forty-eight hours. Introduce it gradually over a week, or as a topper alongside your dog's existing food.",
    variants: [
      { title: "Pack of 7 × 250g", sku: "KUDL-DOG-KK-FRESH-7PK", amount: 1299 },
      { title: "Pack of 14 × 250g", sku: "KUDL-DOG-KK-FRESH-14PK", amount: 2399 },
    ],
  },
  {
    title: "Royal Canin Gastrointestinal Dry Dog Food",
    handle: "royal-canin-gastrointestinal-dog",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Food",
    item: "Prescription Diet",
    pharmacyItem: { column: "Prescription Diet", item: "Gastro Intestinal" },
    brand: "Royal Canin",
    category: "food",
    breeds: ALL_BREEDS,
    rating: 4.8,
    reviewCount: 389,
    image: "kibbleBowlBlue",
    weight: 2000,
    description:
      "A veterinary therapeutic diet for dogs with acute or chronic digestive upset — persistent loose stools, poor nutrient absorption, or recovery after a bout of gastroenteritis. The formula pairs highly digestible protein and starch sources with a low fat level, so the gut has less work to do at each meal, and adds a prebiotic blend of fructo-oligosaccharides and psyllium to feed beneficial gut flora and firm up stool consistency. Electrolytes are elevated to help replace what is lost during a bout of diarrhoea, and the energy density is high enough that a dog with a reduced appetite still meets its needs from a small bowl. This is a prescription product: it should be fed on the advice of a veterinarian, who will set the duration and review whether your dog moves back to a maintenance diet or stays on it long term.",
    variants: [
      { title: "2kg", sku: "KUDL-DOG-RC-GI-2KG", amount: 1899 },
      { title: "7.5kg", sku: "KUDL-DOG-RC-GI-7.5KG", amount: 5799 },
    ],
  },

  // ─── Dog Treats & Chews ──────────────────────────────────────────────────
  {
    title: "Pedigree Biscrok Biscuits — Chicken",
    handle: "pedigree-biscrok-biscuits-chicken",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Treats & Chews",
    item: "Biscuits & Cookies",
    brand: "Pedigree",
    category: "treats",
    breeds: ALL_BREEDS,
    rating: 4.2,
    reviewCount: 3106,
    image: "boneBiscuitsPink",
    weight: 500,
    description:
      "Crunchy oven-baked bone-shaped biscuits in a chicken flavour, made for the small everyday moments — coming back inside, settling in the crate, letting you check a paw. The hard texture gives a satisfying snap that most dogs work at rather than swallow whole, and that chewing action gives the gums a mild mechanical scrub along the way. Fortified with calcium for bone strength and vitamin E as an antioxidant. Biscuits are a treat, not a meal: keep all treats to under ten percent of your dog's daily calories and take the difference out of the main bowl, because biscuit calories are the quietest way a dog puts on weight. Break a biscuit in half for a small breed or a puppy. Store in the resealable pack in a cool, dry cupboard so they stay crisp.",
    variants: [
      { title: "500g", sku: "KUDL-DOG-BISCROK-500G", amount: 199 },
      { title: "1kg", sku: "KUDL-DOG-BISCROK-1KG", amount: 359 },
    ],
  },
  {
    title: "Bark Out Loud Himalayan Yak Milk Chew Bar",
    handle: "bark-out-loud-yak-milk-chew-bar",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Treats & Chews",
    item: "Bones & Chews",
    brand: "Bark Out Loud",
    category: "treats",
    breeds: ALL_BREEDS,
    rating: 4.6,
    reviewCount: 1247,
    image: "treatsInBowl",
    weight: 250,
    description:
      "A traditional Himalayan hard cheese chew, made by curdling yak and cow milk with lime juice, pressing out the whey and drying the block slowly for weeks. The result is dense, almost odourless, and lasts far longer than a rawhide — most medium dogs work at one bar for an hour or more, which makes it genuinely useful for a dog that needs occupying while you are on a call or crating overnight. Just three ingredients, no starch binders, no smoke flavouring and no preservatives. Match the bar size to your dog and take it away once it is small enough to swallow whole; the final nub can be microwaved for forty seconds to puff into a light, crunchy popper. Always supervise a chew session, and offer these in moderation to dogs that are sensitive to dairy.",
    variants: [
      { title: "Small (2 bars)", sku: "KUDL-DOG-YAK-S", amount: 349 },
      { title: "Medium (2 bars)", sku: "KUDL-DOG-YAK-M", amount: 499 },
      { title: "Large (1 bar)", sku: "KUDL-DOG-YAK-L", amount: 599 },
    ],
  },
  {
    title: "Carniwel Dental Sticks — Mint & Parsley",
    handle: "carniwel-dental-sticks-mint-parsley",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Treats & Chews",
    item: "Dental Treats",
    pharmacyItem: { column: "Dogs (Pharmacy)", item: "Oral Care" },
    brand: "Carniwel",
    category: "treats",
    breeds: ALL_BREEDS,
    rating: 4.4,
    reviewCount: 908,
    image: "boneBiscuitsPink",
    weight: 180,
    description:
      "A daily dental chew with an X-shaped ridged profile, designed so the texture reaches the back molars and the gum line where plaque actually accumulates and where a toothbrush is hardest to use. Chewing scrapes soft plaque before it mineralises into tartar, while mint and parsley extracts work on the smell of the breath and sodium tripolyphosphate binds the salivary calcium that would otherwise harden into a deposit. One stick a day is the intended dose, sized to your dog's weight. This supports oral hygiene but does not replace it — it will not remove tartar that has already hardened, and a dog with red gums, a broken tooth or genuinely foul breath needs a veterinary dental examination rather than a chew. Supervise while chewing and keep fresh water available.",
    variants: [
      { title: "Small — 7 sticks", sku: "KUDL-DOG-DENTAL-S-7", amount: 249 },
      { title: "Medium — 7 sticks", sku: "KUDL-DOG-DENTAL-M-7", amount: 329 },
      { title: "Large — 7 sticks", sku: "KUDL-DOG-DENTAL-L-7", amount: 399 },
    ],
  },
  {
    title: "Petstar Chicken Jerky Strips",
    handle: "petstar-chicken-jerky-strips",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Treats & Chews",
    item: "Jerky Treats",
    brand: "Petstar",
    category: "treats",
    breeds: ALL_BREEDS,
    rating: 4.3,
    reviewCount: 1522,
    image: "dogLicking",
    weight: 200,
    description:
      "Whole chicken breast fillets, sliced thin and air-dried until leathery, with nothing else added. Because the moisture is drawn out slowly rather than baked off, the strips stay pliable and hold a concentrated meaty smell that reliably gets the attention of a distracted dog — which is exactly what you want from a high-value reward at the vet, on a busy street, or when teaching a recall that has to beat a squirrel. Single-ingredient and grain-free, so these are also a safe choice during an elimination diet as long as chicken is not the suspect protein. Tear a strip into several small pieces rather than giving it whole: for training purposes the number of repetitions matters far more than the size of each reward. Reseal the pack and keep it cool and dry.",
    variants: [
      { title: "70g", sku: "KUDL-DOG-JERKY-70G", amount: 229 },
      { title: "200g", sku: "KUDL-DOG-JERKY-200G", amount: 549 },
    ],
  },
  {
    title: "Henlo Soft Training Bites — Chicken & Cheese",
    handle: "henlo-soft-training-bites",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Treats & Chews",
    item: "Henlo Treats",
    brand: "Henlo",
    category: "treats",
    breeds: ALL_BREEDS,
    rating: 4.7,
    reviewCount: 2033,
    image: "treatsInBowl",
    weight: 150,
    description:
      "Pea-sized soft treats made for the mechanics of training rather than for snacking. Each bite is roughly two calories, so a full session of fifty repetitions costs about a hundred calories instead of derailing the day's feeding; the texture is soft enough to swallow in a second, which keeps the tempo of a session up and holds a dog's attention between cues. Chicken and cheese give a strong enough aroma to work as a reward in a distracting environment, and the pieces do not crumble in a pocket or a treat pouch. Grain-free, no artificial colours. Split a handful into a pouch before you start so you are not fumbling with a pack mid-cue, and remember to deduct training treats from the day's main meal — a productive week of training is enough to nudge a dog's weight if you do not.",
    variants: [
      { title: "150g", sku: "KUDL-DOG-HENLO-BITES-150G", amount: 279 },
      { title: "350g", sku: "KUDL-DOG-HENLO-BITES-350G", amount: 549 },
    ],
  },

  // ─── Walk & Travel Essentials ────────────────────────────────────────────
  {
    title: "Skatrs Padded Adjustable Collar",
    handle: "skatrs-padded-adjustable-collar",
    petType: "dogs",
    tree: "dogs",
    column: "Walk & Travel Essentials",
    item: "Collars",
    brand: "Skatrs",
    category: "accessories",
    rating: 4.4,
    reviewCount: 876,
    image: "puppyTealCollar",
    weight: 120,
    description:
      "An everyday collar in woven nylon webbing with a neoprene-padded inner face, so the edge cannot dig into the neck on a dog that pulls or shakes. The side-release buckle is a glass-filled nylon that stays workable in the wet, the D-ring is welded rather than rolled — a rolled ring is the part that quietly opens under load — and a run of reflective stitching along the webbing picks up headlights on an early morning walk. Adjustable through a wide range so it will follow a growing puppy for several months. Measure around the base of the neck and add about two finger-widths of room; you should be able to slide two fingers flat under the fitted collar. Check the fit every fortnight on a puppy. Hand wash in mild soap and dry away from direct sun.",
    variants: [
      { title: "Small (25-38cm)", sku: "KUDL-DOG-COLLAR-S", amount: 449 },
      { title: "Medium (33-50cm)", sku: "KUDL-DOG-COLLAR-M", amount: 549 },
      { title: "Large (43-66cm)", sku: "KUDL-DOG-COLLAR-L", amount: 649 },
    ],
  },
  {
    title: "Skatrs Reflective Nylon Leash — 1.5m",
    handle: "skatrs-reflective-nylon-leash",
    petType: "dogs",
    tree: "dogs",
    column: "Walk & Travel Essentials",
    item: "Leashes",
    brand: "Skatrs",
    category: "accessories",
    rating: 4.5,
    reviewCount: 1094,
    image: "leashOnWood",
    weight: 200,
    description:
      "A fixed-length lead at one and a half metres — long enough to let a dog walk at its own pace beside you, short enough that you keep real control at a kerb or in a crowded market, which is the trade-off a retractable lead gets wrong. The webbing is double-stitched at every load point and finished with a padded neoprene handle so a sudden lunge does not burn your palm, plus a second traffic handle low on the lead for pulling a dog in close and quick. The swivel snap hook is zinc alloy with a spring gate rated well above the pull of a large breed. Reflective thread runs the full length. Pair it with a harness rather than a collar for any dog that pulls hard, to keep the load off the neck and trachea. Machine washable in a laundry bag.",
    variants: [{ title: "1.5m × 20mm", sku: "KUDL-DOG-LEASH-15M", amount: 599 }],
  },
  {
    title: "Skatrs No-Pull Mesh Harness",
    handle: "skatrs-no-pull-mesh-harness",
    petType: "dogs",
    tree: "dogs",
    column: "Walk & Travel Essentials",
    item: "Harnesses",
    brand: "Skatrs",
    category: "accessories",
    breeds: ALL_BREEDS,
    rating: 4.6,
    reviewCount: 1338,
    image: "harnessGolden",
    weight: 280,
    description:
      "A step-in harness with a breathable padded mesh chest plate that spreads the pull across the sternum and ribs instead of loading the throat, which is the single most useful change you can make for a dog that leans into a collar — and matters more still for the flat-faced breeds whose airways are already compromised. Two attachment points do different jobs: the steel ring on the back is for relaxed walking, and the front chest ring turns a dog's own forward pull into a gentle sideways redirect, which is what makes it a training tool rather than just a restraint. Four adjustment points let you fit the neck and girth independently. Measure the widest part of the chest behind the front legs and size up if you are between sizes. Two fingers should slide under any strap.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-HARNESS-S", amount: 899 },
      { title: "Medium", sku: "KUDL-DOG-HARNESS-M", amount: 1099 },
      { title: "Large", sku: "KUDL-DOG-HARNESS-L", amount: 1299 },
    ],
  },
  {
    title: "KUDL Smart GPS Tracker for Collars",
    handle: "kudl-smart-gps-tracker",
    petType: "dogs",
    tree: "dogs",
    column: "Walk & Travel Essentials",
    item: "GPS Tracker",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.1,
    reviewCount: 267,
    image: "harnessDachshund",
    weight: 90,
    description:
      "A lightweight tracker that clips onto any collar or harness strap up to twenty-five millimetres wide and reports live location to your phone, so a dog that slips a gate is a search you can actually run rather than a night of driving around calling a name. Location comes from GPS with cellular assistance, and switches to Bluetooth proximity for close-range hunting once you are within about fifty metres — useful when the dog is somewhere in a neighbour's hedge. You can draw a safe zone around the house and get an alert the moment the tracker leaves it, and review a walk route afterwards as a track on a map. Rated IPX7, so rain and puddles are fine. Battery runs roughly five to seven days depending on how often it reports, and charges over USB-C in about two hours. Cellular service needs an active data plan.",
    variants: [{ title: "Standard", sku: "KUDL-DOG-GPS-STD", amount: 3499 }],
  },
  {
    title: "Bark Out Loud Travel Carrier Shoulder Bag",
    handle: "bark-out-loud-travel-carrier-bag",
    petType: "dogs",
    tree: "dogs",
    column: "Walk & Travel Essentials",
    item: "Carriers & Travel Supplies",
    brand: "Bark Out Loud",
    category: "accessories",
    breeds: SMALL_BREEDS,
    rating: 4.3,
    reviewCount: 412,
    image: "dogInShoulderBag",
    weight: 900,
    description:
      "A soft-sided carrier for small dogs up to about seven kilograms, built for the vet run, the auto ride and the cabin of a train. Mesh panels on three sides keep air moving and let a nervous dog see out, which usually settles it faster than a closed box; a roll-down privacy flap covers a panel when the opposite is true. Inside, a padded and removable fleece base lifts out for washing and an internal safety tether clips to the harness so a dog cannot bolt the moment the zip opens — that clip is the part people miss until it matters. The frame holds its shape when the bag is set down, and the shoulder strap is padded with a non-slip pad. Never leave a dog in a closed carrier in a parked vehicle, and let a first-time traveller nap in it at home before the first real journey.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-CARRIER-S", amount: 1899 },
      { title: "Medium", sku: "KUDL-DOG-CARRIER-M", amount: 2299 },
    ],
  },
  {
    title: "KUDL Foldable Wire Crate with Divider",
    handle: "kudl-foldable-wire-crate",
    petType: "dogs",
    tree: "dogs",
    column: "Walk & Travel Essentials",
    item: "Cages & Crates",
    brand: "KUDL Essentials",
    category: "accessories",
    breeds: ALL_BREEDS,
    rating: 4.5,
    reviewCount: 534,
    image: "dogInCrate",
    weight: 9000,
    description:
      "A powder-coated wire crate that gives a dog a den of its own — the single most useful piece of equipment for house-training a puppy, for giving a dog a place to decompress away from visitors, and for crate rest after surgery. Two doors let you site it in a corner and still get access, and both latch with a slide bolt a clever dog cannot nose open. The included divider panel is the reason to buy a crate sized for the adult dog rather than the puppy: you shrink the usable space so a puppy will not soil one end and sleep in the other, then move the panel out as it grows. A removable plastic tray slides out for cleaning. Folds flat in under a minute for storage or a car boot. Introduce it with meals and treats inside and the door open — a crate should never be used as a punishment.",
    variants: [
      { title: "Medium (76cm)", sku: "KUDL-DOG-CRATE-M", amount: 3499 },
      { title: "Large (91cm)", sku: "KUDL-DOG-CRATE-L", amount: 4499 },
      { title: "XL (107cm)", sku: "KUDL-DOG-CRATE-XL", amount: 5799 },
    ],
  },

  // ─── Dog Toys ────────────────────────────────────────────────────────────
  {
    title: "Skatrs Natural Rubber Chew Bone",
    handle: "skatrs-natural-rubber-chew-bone",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Toys",
    item: "Chew Toys",
    brand: "Skatrs",
    category: "toys",
    breeds: ALL_BREEDS,
    rating: 4.4,
    reviewCount: 967,
    image: "puppyWithToy",
    weight: 220,
    description:
      "A solid chew bone moulded from natural rubber with enough give to flex under a determined jaw and enough resilience to spring back rather than shear off in pieces. Chewing is a need rather than a habit — a dog denied an outlet for it finds the skirting board or a shoe — and a rubber bone is the outlet that survives the longest. The ridged surface massages the gums and rubs at soft plaque along the way. Textured lengthwise grooves take a smear of nut butter or soft cheese, which turns ten minutes of chewing into forty. Free of BPA and phthalates. Size it up rather than down: a bone a dog can fit fully into its mouth is a choking risk. Inspect it weekly and retire it once chunks can be torn free, and always supervise a heavy chewer.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-RUBBERBONE-S", amount: 349 },
      { title: "Medium", sku: "KUDL-DOG-RUBBERBONE-M", amount: 449 },
      { title: "Large", sku: "KUDL-DOG-RUBBERBONE-L", amount: 549 },
    ],
  },
  {
    title: "KUDL Treat Dispensing Puzzle Ball",
    handle: "kudl-treat-dispensing-puzzle-ball",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Toys",
    item: "Treat Dispensing Toys",
    brand: "KUDL Essentials",
    category: "toys",
    breeds: ALL_BREEDS,
    rating: 4.5,
    reviewCount: 721,
    image: "tennisBall",
    weight: 180,
    description:
      "A hollow ball that releases kibble a few pieces at a time as a dog nudges and rolls it, turning an ordinary meal into fifteen or twenty minutes of problem-solving. That matters more than it sounds: mental work tires a dog in a way a walk alone does not, and slowing a fast eater down reduces the gulped air that leaves a dog uncomfortable and bloated after a bowl. A twist collar adjusts the opening across three difficulty levels, so you can start it easy enough that a first-timer succeeds within a minute and tighten it once the dog has the idea. Moulded in food-safe ABS with a soft rubber outer ring that keeps it quiet on a hard floor and lets it bounce unpredictably. Dishwasher-safe on the top rack. Fill it with the dog's own dry food rather than extra treats so the day's calories stay where they were.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-PUZZLEBALL-S", amount: 499 },
      { title: "Large", sku: "KUDL-DOG-PUZZLEBALL-L", amount: 649 },
    ],
  },
  {
    title: "Bark Out Loud Plush Squirrel with Squeaker",
    handle: "bark-out-loud-plush-squirrel",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Toys",
    item: "Plush & Soft Toys",
    brand: "Bark Out Loud",
    category: "toys",
    breeds: ALL_BREEDS,
    rating: 4.2,
    reviewCount: 1183,
    image: "dogWithPlushToy",
    weight: 140,
    description:
      "A soft-bodied squirrel with a long floppy tail and an internal squeaker, built for the dogs whose favourite game is carrying something soft around the house and shaking it. The double-layered fabric shell is reinforced with a hidden lining and the seams are stitched twice, so it stands up to ordinary play far better than a single-layer plush, and there are no plastic eyes or sewn-on beads to work loose and be swallowed. The tail is deliberately long enough to grab for a gentle tug game. Filled with polyester fibre and free of stuffing beads. This is a companion toy rather than a chew toy — a determined shredder will get through it, so keep it for supervised play, retire it once a seam opens, and wash it in a laundry bag on a cool cycle to keep the squeaker working.",
    variants: [{ title: "Standard", sku: "KUDL-DOG-PLUSH-SQUIRREL", amount: 399 }],
  },
  {
    title: "Skatrs Cotton Rope Tug Toy",
    handle: "skatrs-cotton-rope-tug-toy",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Toys",
    item: "Rope & Tug Toys",
    brand: "Skatrs",
    category: "toys",
    breeds: LARGE_BREEDS,
    rating: 4.3,
    reviewCount: 645,
    image: "puppyWithToy",
    weight: 260,
    description:
      "A three-knot tug rope braided from thick undyed cotton strands, made for the two-player game most dogs love best. Tug is worth playing properly: it burns real energy in a small space, and because you control when it starts and stops it is one of the easiest ways to practise an impulse-control cue like drop with a dog that is genuinely excited rather than bored. The knots also give a dog something to work between the back teeth, and the loose cotton fibres act as a mild floss along the gum line. Undyed and free of chemical treatment, so the fibres that inevitably come loose are cotton and nothing else. Keep the game low and horizontal rather than lifting a dog off its front feet, stop while the dog still wants more, and retire the rope once it frays badly — long swallowed strands are a genuine hazard.",
    variants: [
      { title: "Medium", sku: "KUDL-DOG-ROPE-M", amount: 299 },
      { title: "Large", sku: "KUDL-DOG-ROPE-L", amount: 399 },
    ],
  },
  {
    title: "KUDL Bounce Fetch Ball Set — Pack of 3",
    handle: "kudl-bounce-fetch-ball-set",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Toys",
    item: "Ball & Fetch Toys",
    brand: "KUDL Essentials",
    category: "toys",
    breeds: ALL_BREEDS,
    rating: 4.6,
    reviewCount: 1502,
    image: "tennisBall",
    weight: 300,
    description:
      "Three high-bounce balls in a felted, grippy cover, sized to sit comfortably in a standard ball thrower so you can send a fetch further than an arm manages and give a high-energy dog a real run in a short window. The rubber core is solid rather than hollow, which is what stops it collapsing into a swallowable flap once the cover starts to wear — the failure mode that makes worn tennis balls genuinely dangerous. Visible on grass and floatable in water. Buying them as a set matters in practice: a second ball in your pocket is how you get the first one back from a dog that would rather keep it. Choose the size a dog cannot fit entirely behind its molars, replace a ball once the cover splits, and take them away between sessions so the novelty holds.",
    variants: [
      { title: "Medium 6.5cm — 3 pack", sku: "KUDL-DOG-FETCHBALL-M3", amount: 449 },
      { title: "Large 7.5cm — 3 pack", sku: "KUDL-DOG-FETCHBALL-L3", amount: 549 },
    ],
  },

  // ─── Dog Clothing ────────────────────────────────────────────────────────
  {
    title: "Bark Out Loud Printed Cotton Tee",
    handle: "bark-out-loud-printed-cotton-tee",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Clothing",
    item: "Tshirts & Shirts",
    brand: "Bark Out Loud",
    category: "accessories",
    rating: 4.1,
    reviewCount: 389,
    image: "frenchieYellowShirt",
    weight: 130,
    description:
      "A soft single-jersey cotton tee cut for a dog's shape rather than adapted from a human pattern — longer along the back, scooped clear underneath so it stays dry, and roomy at the shoulder so the front legs move freely at a trot. Beyond looking good in photographs, a thin tee has two real uses: it keeps loose hair off furniture during a heavy shedding season, and it stops a dog worrying at a healing patch of skin without the misery of a plastic cone. Flatlock seams sit flush so nothing rubs a bare belly, and the neck is ribbed to hold shape after washing. Measure the back from collar to tail base and the widest part of the chest, and size up if between sizes. Machine washable cold, tumble dry low. Take it off for unsupervised time and for outdoor play in the heat.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-TEE-S", amount: 499 },
      { title: "Medium", sku: "KUDL-DOG-TEE-M", amount: 599 },
      { title: "Large", sku: "KUDL-DOG-TEE-L", amount: 699 },
    ],
  },
  {
    title: "KUDL Fleece Hoodie",
    handle: "kudl-fleece-hoodie",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Clothing",
    item: "Hoodies",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.4,
    reviewCount: 611,
    image: "frenchieYellowHoodie",
    weight: 260,
    description:
      "A brushed-fleece hoodie for cold mornings, with a lined hood that a dog can actually wear rather than one that flops uselessly to the side. The fleece traps warm air without much weight, which suits the dogs that genuinely feel the cold — thin-coated breeds, small dogs with a high surface-area-to-body ratio, seniors, and any dog recently clipped short. A cutout at the back sits clear of the collar and harness ring so you can attach a lead without lifting the garment, and a ribbed hem holds position instead of riding up on a walk. Pull-on styling over the head, with generous leg openings so an older dog is not wrestled into it. Measure the back length and chest girth before ordering. Machine wash cold on a gentle cycle and dry flat to keep the fleece pile from matting; skip the fabric softener, which flattens the loft that does the insulating.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-HOODIE-S", amount: 799 },
      { title: "Medium", sku: "KUDL-DOG-HOODIE-M", amount: 899 },
      { title: "Large", sku: "KUDL-DOG-HOODIE-L", amount: 999 },
    ],
  },
  {
    title: "KUDL Quilted Winter Jacket — Water Resistant",
    handle: "kudl-quilted-winter-jacket",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Clothing",
    item: "Jackets",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.5,
    reviewCount: 448,
    image: "pugKnitScarf",
    weight: 420,
    description:
      "A two-layer winter jacket: a quilted polyfill body for insulation under a water-resistant ripstop shell, so a dog stays warm through a cold, damp walk instead of warm for the first ten minutes and then wet. The cut covers the chest and belly — the areas that actually lose heat against cold ground — and a high collar shields the throat. Adjustment is by two hook-and-loop belly straps rather than a single strap, which is what keeps the jacket square on the body when a dog runs rather than letting it rotate to one side. A harness slot through the back panel means the lead attaches to the harness underneath and the jacket does not take the load. Reflective piping along both flanks for winter dusk. Machine wash cold, air dry; do not iron the shell. Check the fit over a thick coat before the first outing.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-JACKET-S", amount: 1199 },
      { title: "Medium", sku: "KUDL-DOG-JACKET-M", amount: 1399 },
      { title: "Large", sku: "KUDL-DOG-JACKET-L", amount: 1599 },
    ],
  },
  {
    title: "Bark Out Loud Festive Bandana Set — Pack of 2",
    handle: "bark-out-loud-festive-bandana-set",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Clothing",
    item: "Bandanas & Bow-ties",
    brand: "Bark Out Loud",
    category: "accessories",
    rating: 4.0,
    reviewCount: 297,
    image: "frenchieYellowShirt",
    weight: 80,
    description:
      "Two reversible cotton bandanas in a block-printed festive pattern, made as slip-on collar covers rather than as scarves you knot around a dog's neck. That distinction matters: a slip-on threads onto the collar you already fitted, so there is no second thing around the throat and nothing that can tighten if it catches on a branch or a fence. Double-sided, giving four looks from two pieces, and hemmed on all edges so the cotton does not fray after a few washes. Pre-washed to take the shrinkage out before it reaches you. Fits collars up to twenty-five millimetres wide. Practical rather than purely decorative for one small reason — a brightly patterned dog is easier to pick out in a crowded park. Machine washable cold, warm iron on the reverse if you want it crisp. Remove it for unsupervised time and for water play.",
    variants: [
      { title: "Small/Medium — 2 pack", sku: "KUDL-DOG-BANDANA-SM2", amount: 349 },
      { title: "Large — 2 pack", sku: "KUDL-DOG-BANDANA-L2", amount: 399 },
    ],
  },

  // ─── Grooming & Hygiene ──────────────────────────────────────────────────
  {
    title: "Himalaya Erina EP Herbal Dog Shampoo",
    handle: "himalaya-erina-ep-dog-shampoo",
    petType: "dogs",
    tree: "dogs",
    column: "Grooming & Hygiene",
    item: "Shampoos & Conditioners",
    brand: "Himalaya",
    category: "grooming-health",
    rating: 4.4,
    reviewCount: 1832,
    image: "shampooBottles",
    weight: 220,
    description:
      "A pH-balanced herbal shampoo formulated for canine skin, which sits at a markedly different pH from human skin — the reason a human shampoo, however gentle, leaves a dog's coat dull and its skin itchy. Neem and eucalyptus extracts give mild antimicrobial and deodorising action, while methyl salicylate helps settle the low-grade irritation behind persistent scratching. It lathers well in hard water and rinses out cleanly, which is more important than it sounds: residue left in a thick undercoat is a common cause of the flaking owners mistake for dandruff. Free of parabens and harsh sulphates. Wet the coat thoroughly, work the lather in from the neck backwards, keep it well clear of the eyes and ear canals, and rinse twice. Most healthy dogs need bathing only every three to four weeks; more often than that strips the protective coat oils.",
    variants: [
      { title: "200ml", sku: "KUDL-DOG-SHAMPOO-200ML", amount: 249 },
      { title: "500ml", sku: "KUDL-DOG-SHAMPOO-500ML", amount: 499 },
    ],
  },
  {
    title: "KUDL Tick & Flea Spot-On Solution",
    handle: "kudl-tick-flea-spot-on",
    petType: "dogs",
    tree: "dogs",
    column: "Grooming & Hygiene",
    item: "Tick & Flea Solutions",
    pharmacyItem: { column: "Preventive Care", item: "Tick and flea" },
    brand: "KUDL Essentials",
    category: "grooming-health",
    breeds: ALL_BREEDS,
    rating: 4.5,
    reviewCount: 1076,
    image: "dogWithBottle",
    weight: 40,
    description:
      "A monthly topical treatment applied to the skin between the shoulder blades, where it spreads through the coat's oil layer and keeps working for about four weeks. It kills adult fleas and ticks on contact rather than requiring a bite, which is what breaks the flea life cycle in the house — the reason a single treatment feels like it has failed is almost always the eggs and larvae already in the carpet and bedding, not the product. Ticks matter for more than irritation: they transmit ehrlichiosis and babesiosis, and prevention is far simpler than treating either. Part the hair and apply directly to skin, not onto the coat, and keep the dog dry and unbathed for forty-eight hours afterwards. Dose strictly by weight band, treat every dog in the household on the same day, and wash bedding hot in the same week. Never use a dog spot-on on a cat.",
    variants: [
      { title: "Up to 10kg — 3 pipettes", sku: "KUDL-DOG-SPOTON-S3", amount: 649 },
      { title: "10-25kg — 3 pipettes", sku: "KUDL-DOG-SPOTON-M3", amount: 749 },
      { title: "Over 25kg — 3 pipettes", sku: "KUDL-DOG-SPOTON-L3", amount: 849 },
    ],
  },
  {
    title: "Skatrs Self-Cleaning Slicker Brush",
    handle: "skatrs-self-cleaning-slicker-brush",
    petType: "dogs",
    tree: "dogs",
    column: "Grooming & Hygiene",
    item: "Brushes & Combs",
    brand: "Skatrs",
    category: "grooming-health",
    breeds: ALL_BREEDS,
    rating: 4.6,
    reviewCount: 2214,
    image: "brushesInBowl",
    weight: 210,
    description:
      "A slicker brush with fine angled stainless pins set in a flexible cushion pad, for lifting the dead undercoat that a comb slides straight over. This is the tool that actually prevents mats rather than dealing with them afterwards — most matting starts as shed hair trapped against the skin, and getting it out weekly is what keeps a double coat comfortable through a shedding season. The pins are bent and ball-tipped so they part the coat instead of scoring the skin, and the cushion backing gives way if you press too hard. A retract button pulls the pins back through the head so the collected hair lifts off in one pad rather than being picked out by hand. Brush in the direction the coat lies, in short overlapping strokes, holding the skin taut in front of the brush. Stop if the skin pinks up; a slicker used too firmly causes brush burn.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-SLICKER-S", amount: 449 },
      { title: "Large", sku: "KUDL-DOG-SLICKER-L", amount: 549 },
    ],
  },
  {
    title: "KUDL Quiet Nail Clipper & Grinder Set",
    handle: "kudl-nail-clipper-grinder-set",
    petType: "dogs",
    tree: "dogs",
    column: "Grooming & Hygiene",
    item: "Trimmers & Nail Clippers",
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.3,
    reviewCount: 703,
    image: "brushesInBowl",
    weight: 320,
    description:
      "A plier-style clipper in hardened stainless steel paired with a rechargeable diamond-bit grinder, because the two tools do different halves of the job. The clipper takes the length off in one clean cut — a sharp blade cuts, a blunt one crushes the nail and hurts — and its safety stop limits how far the blade closes, which is the guard against catching the quick on a dog whose nails are dark and whose quick you cannot see. The grinder then rounds the cut edge smooth so nothing snags on upholstery, and is the gentler option for a dog that has learned to dread the clipper's snap: it runs quietly at two speeds with low vibration. Trim a little and often rather than a lot occasionally; the quick recedes as the nail shortens. If a nail bleeds, press styptic powder to it. USB-C charging, about ninety minutes for a full charge.",
    variants: [{ title: "Standard set", sku: "KUDL-DOG-NAILSET-STD", amount: 1299 }],
  },
  {
    title: "KUDL Paw Butter Balm with Shea & Coconut",
    handle: "kudl-paw-butter-balm",
    petType: "dogs",
    tree: "dogs",
    column: "Grooming & Hygiene",
    item: "Paw & Nail care",
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.5,
    reviewCount: 856,
    image: "shampooBottles",
    weight: 60,
    description:
      "A thick balm of shea butter, coconut oil, beeswax and vitamin E for paw pads that have gone dry, rough or cracked. Pads take more punishment than any other skin on a dog — hot pavement in summer, grit and cold in winter, and the constant abrasion of walking on concrete rather than on soil — and once a crack opens it is both painful and an easy route for infection. The balm melts at body heat and soaks in rather than sitting greasy on the surface, and a layer applied before a walk gives some barrier against hot tarmac and rough ground. Also useful on a dry nose or a callused elbow. Massage a pea-sized amount into each pad and between the toes, ideally after a walk when the dog is settled, and distract it for a few minutes so the balm absorbs rather than being licked off. All ingredients are food-grade and safe if some is licked.",
    variants: [
      { title: "50g", sku: "KUDL-DOG-PAWBALM-50G", amount: 399 },
      { title: "100g", sku: "KUDL-DOG-PAWBALM-100G", amount: 649 },
    ],
  },
  {
    title: "KUDL Grooming Wipes — Fragrance Free",
    handle: "kudl-grooming-wipes-fragrance-free",
    petType: "dogs",
    tree: "dogs",
    column: "Grooming & Hygiene",
    item: "Towels & Wipes",
    brand: "KUDL Essentials",
    category: "grooming-health",
    rating: 4.2,
    reviewCount: 1341,
    image: "shampooBottles",
    weight: 350,
    description:
      "Thick, textured wipes soaked in a mild pH-balanced cleanser with aloe and vitamin E, for all the cleaning that happens between baths — muddy paws at the door, a dirty rear, a face that needs the tear staining lifted from under the eyes. Because a dog should not be bathed every week, a wipe is what keeps it presentable without stripping coat oils, and it is far quicker than a bath for the dogs that dread one. Fragrance-free and alcohol-free on purpose: perfume is the usual culprit when a wipe leaves skin irritated, and a scented product is unpleasant for an animal whose sense of smell dwarfs yours. The cloth is embossed to trap grit rather than push it around. Use a fresh wipe per area, keep them out of the ears and eyes, and close the lid firmly so the remaining wipes stay damp. Do not flush.",
    variants: [
      { title: "80 wipes", sku: "KUDL-DOG-WIPES-80", amount: 299 },
      { title: "2 × 80 wipes", sku: "KUDL-DOG-WIPES-160", amount: 549 },
    ],
  },

  // ─── Bowls & Feeders ─────────────────────────────────────────────────────
  {
    title: "KUDL Stainless Steel Anti-Skid Bowl",
    handle: "kudl-stainless-steel-anti-skid-bowl",
    petType: "dogs",
    tree: "dogs",
    column: "Bowls & Feeders",
    item: "Steel bowls",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.7,
    reviewCount: 2687,
    image: "dogAtBowl",
    weight: 480,
    description:
      "A food-grade stainless steel bowl with a bonded silicone ring on the base, so an enthusiastic eater cannot push it across the kitchen floor. Steel is the right material for a feeding bowl and the reasoning is straightforward: it does not scratch into the microscopic grooves that harbour bacteria the way plastic does, it does not leach, it will not crack when dropped, and it can be washed hot enough to actually sanitise. Plastic bowls are also a recognised trigger for the contact irritation that shows up as a pale, sore patch on a dog's chin. The rolled rim is smooth against the muzzle and stiffens the wall so the bowl holds shape for years. Wide and shallow rather than deep and narrow, which suits a broad muzzle and lets a dog eat without pressing its whiskers into the sides. Dishwasher safe; wash daily, as a water bowl grows a biofilm within about a day.",
    variants: [
      { title: "350ml", sku: "KUDL-DOG-STEELBOWL-350", amount: 299 },
      { title: "900ml", sku: "KUDL-DOG-STEELBOWL-900", amount: 449 },
      { title: "1.8L", sku: "KUDL-DOG-STEELBOWL-1800", amount: 649 },
    ],
  },
  {
    title: "KUDL Slow Feeder Maze Bowl",
    handle: "kudl-slow-feeder-maze-bowl",
    petType: "dogs",
    tree: "dogs",
    column: "Bowls & Feeders",
    item: "Slow Feeders & Licky Mats",
    brand: "KUDL Essentials",
    category: "accessories",
    breeds: LARGE_BREEDS,
    rating: 4.5,
    reviewCount: 1194,
    image: "kibbleBowlBlue",
    weight: 260,
    description:
      "A bowl with a raised maze moulded into the base, so a dog has to nose kibble out of the channels a few pieces at a time. A meal that took ninety seconds typically stretches to eight or ten minutes, and that slowdown does real work: less swallowed air means less of the bloating and post-meal discomfort that follows a gulped bowl, and in deep-chested breeds it is one of the simple risk-reduction steps against gastric torsion. It also gives an over-eager dog something to think about, which takes the edge off mealtime pushiness in a multi-dog house. Moulded in BPA-free food-grade plastic with a non-slip base ring. Start with the shallower pattern if your dog gives up easily, and rinse it right after a wet meal — the channels are the point of the bowl, and food dries hard in them. Top-rack dishwasher safe.",
    variants: [
      { title: "Small", sku: "KUDL-DOG-SLOWFEED-S", amount: 449 },
      { title: "Large", sku: "KUDL-DOG-SLOWFEED-L", amount: 599 },
    ],
  },
  {
    title: "KUDL Filtered Pet Water Fountain — 2.5L",
    handle: "kudl-filtered-pet-water-fountain",
    petType: "dogs",
    tree: "dogs",
    column: "Bowls & Feeders",
    item: "Water Fountain",
    brand: "KUDL Essentials",
    category: "accessories",
    rating: 4.4,
    reviewCount: 592,
    image: "dogAtBowl",
    weight: 1100,
    description:
      "A circulating water fountain that holds two and a half litres and keeps it moving through a replaceable carbon and cotton filter. Moving water is more inviting than a still bowl for most animals, and that is the whole value of a fountain — a pet that drinks more is a pet with a lower risk of the urinary and kidney trouble that chronic mild dehydration feeds, which is why fountains are recommended most often for cats and for older dogs. The filter takes out hair, sediment and the chlorine taste that puts some animals off tap water. The pump runs at under forty decibels, quiet enough for a bedroom, and a low-water cutout stops it running dry and burning out. Rinse the basin and change the filter about every three to four weeks, sooner in a hard-water area, and strip and clean the pump impeller monthly — a neglected fountain is dirtier than a bowl you wash daily.",
    variants: [{ title: "2.5L", sku: "KUDL-PET-FOUNTAIN-2.5L", amount: 2299 }],
  },

  // ─── Dog Beds & Mats ─────────────────────────────────────────────────────
  {
    title: "KUDL Orthopaedic Bolster Bed",
    handle: "kudl-orthopaedic-bolster-bed",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Beds & Mats",
    item: "Beds",
    brand: "KUDL Essentials",
    category: "accessories",
    breeds: ALL_BREEDS,
    rating: 4.7,
    reviewCount: 1408,
    image: "dogInGreyBed",
    weight: 3200,
    description:
      "A bed built on a solid slab of high-density orthopaedic foam rather than loose fibre fill, with raised bolsters on three sides for a dog that likes to sleep with its head propped. The distinction matters most for the dogs that need a bed most: fibre fill compresses within months and leaves an older dog with arthritic hips or elbows effectively lying on the floor, while a foam core keeps supporting weight and spreads pressure off the joints and bony points. Big dogs and lean, deep-chested breeds get the same benefit. The cover is a tight-weave upholstery fabric over a water-resistant inner liner, and it unzips fully for machine washing — that liner is what saves the foam from an accident or a wet dog. A non-slip base keeps the bed from sliding on tile. Measure your dog stretched flat and add fifteen centimetres for a bed it can actually lie out in.",
    variants: [
      { title: "Medium (70×55cm)", sku: "KUDL-DOG-ORTHOBED-M", amount: 2999 },
      { title: "Large (90×65cm)", sku: "KUDL-DOG-ORTHOBED-L", amount: 3999 },
      { title: "XL (110×80cm)", sku: "KUDL-DOG-ORTHOBED-XL", amount: 5299 },
    ],
  },
  {
    title: "KUDL Cooling Gel Mat",
    handle: "kudl-cooling-gel-mat",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Beds & Mats",
    item: "Cooling Mats",
    brand: "KUDL Essentials",
    category: "accessories",
    breeds: ALL_BREEDS,
    rating: 4.2,
    reviewCount: 967,
    image: "dogInRoundBed",
    weight: 1400,
    description:
      "A pressure-activated cooling mat filled with a non-toxic gel that draws heat out of a dog lying on it — no electricity, no freezer, no water to fill. It recharges itself after fifteen or twenty minutes unused, so a dog can move on and off it through a hot afternoon. This is genuinely useful equipment in an Indian summer for the animals that struggle most with heat: thick double coats, black coats, brachycephalic breeds whose short airways make panting inefficient, overweight dogs and seniors. Lay it on the floor, inside a crate, or on top of a bed under a thin sheet. It is a comfort aid, not a treatment — a dog showing heatstroke signs needs shade, cool water and a vet, not a mat. Wipe clean with a damp cloth; do not machine wash, tumble dry or leave it where a determined chewer can puncture the gel layer.",
    variants: [
      { title: "Medium (50×65cm)", sku: "KUDL-DOG-COOLMAT-M", amount: 1099 },
      { title: "Large (65×90cm)", sku: "KUDL-DOG-COOLMAT-L", amount: 1499 },
    ],
  },
  {
    title: "Bark Out Loud Reversible Fleece Blanket",
    handle: "bark-out-loud-reversible-fleece-blanket",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Beds & Mats",
    item: "Cushions & Blankets",
    brand: "Bark Out Loud",
    category: "accessories",
    rating: 4.4,
    reviewCount: 738,
    image: "poodlesInBed",
    weight: 700,
    description:
      "A double-sided fleece blanket, sherpa on one face for winter and smooth microfleece on the other for milder weather, hemmed all round so the edges do not shed lint after washing. The most useful thing about a blanket is that it is the layer you wash: put it over the bed, the sofa cushion or the car seat and the hair, dust and inevitable muddy paw print land on something that fits in a machine rather than on the furniture. It is also the practical way to make a strange place feel familiar — a blanket that already smells of home settles a dog in a hotel room, a boarding kennel or a crate far faster than anything you can buy on arrival. Warm enough to matter for thin-coated and older dogs who seek out heat. Machine wash cold, tumble dry low, no fabric softener as it flattens the pile.",
    variants: [
      { title: "Medium (75×100cm)", sku: "KUDL-DOG-BLANKET-M", amount: 699 },
      { title: "Large (100×140cm)", sku: "KUDL-DOG-BLANKET-L", amount: 999 },
    ],
  },
  {
    title: "KUDL Elevated Mesh Cot Bed",
    handle: "kudl-elevated-mesh-cot-bed",
    petType: "dogs",
    tree: "dogs",
    column: "Dog Beds & Mats",
    item: "Elevated Beds",
    brand: "KUDL Essentials",
    category: "accessories",
    breeds: LARGE_BREEDS,
    rating: 4.3,
    reviewCount: 421,
    image: "dogInRoundBed",
    weight: 2600,
    description:
      "A taut breathable mesh stretched over a powder-coated steel frame, holding a dog about eighteen centimetres clear of the floor. Lifting a dog off the ground does three things a cushioned bed cannot: air moves underneath, so a thick-coated dog stays measurably cooler on a hot night; the dog is up out of floor draughts and off cold tile in winter; and the suspended mesh flexes to spread weight, which takes pressure off hips and elbows without any foam to compress. Nothing absorbs, so it is the easiest bed to keep clean in a house with fleas or a dog with a skin condition — hose it and it dries in minutes. Rust-resistant and rated well above the weight it will carry, and it is equally at home on a balcony or a verandah. Assembles without tools in a couple of minutes and comes apart flat for travel. Check the frame bolts every few months.",
    variants: [
      { title: "Medium (76×61cm)", sku: "KUDL-DOG-COT-M", amount: 1999 },
      { title: "Large (107×76cm)", sku: "KUDL-DOG-COT-L", amount: 2799 },
    ],
  },
]
