/**
 * Icon set. The mobile app uses Feather via @expo/vector-icons; lucide-react is
 * a maintained fork of Feather, so these are the same glyphs. Names mirror the
 * Feather names used in the app to keep the two codebases easy to diff.
 */
export {
  Home,
  LayoutGrid as Grid,
  LayoutGrid,
  List,
  ChevronDown,
  SlidersHorizontal,
  SearchX,
  ShoppingCart,
  User,
  Search,
  ShoppingBag,
  Heart,
  ArrowRight,
  ChevronRight,
  ChevronLeft,
  Truck,
  Shield,
  RefreshCw,
  Minus,
  Plus,
  Trash2,
  Check,
  CheckCircle2 as CheckCircle,
  XCircle,
  Clock,
  Package,
  MapPin,
  Settings,
  LogIn,
  LogOut,
  UserPlus,
  CreditCard,
  AlertCircle,
  X,
  Edit2,
  Tag,
  Loader2,
  Headphones,
  Star,
  Instagram,
  Facebook,
  Mail,
  PawPrint,
  Percent,
  Sparkles,
  Users,
  Smartphone,
  Apple,
  Pill,
} from "lucide-react"
